### ISSUE TITLE
firebird select * stored_procedure not working

### ISSUE THREAD

**Issue by denizgirginer** [ADOdb/ADOdb#91] opened 2015-03-17 15:44 UTC
i have a stored procedure and its return rows like views,  when run script its result some time wrong, some time correct, its not work properly,

**Comment by dregad** [comment] 2015-03-19 07:28
You are not giving sufficient information to troubleshoot the problem. Please provide step-by-step instructions with sample code to reproduce the incorrect behavior.

**Comment by dregad** [comment] 2015-04-20 14:01
Closing since no feedback was given.

**Closed** 2015-04-20 14:00 UTC
