### ISSUE TITLE
Version 5.22.7 does not work with php 8.2.16

### ISSUE THREAD

**Issue by claudedeslandes** [ADOdb/ADOdb#1039] opened 2024-08-06 14:07 UTC
### Description
The Adobo works fin under php 8.1.x ... but not under php.8.2.16

### Environment
- ADOdb version: 5.22.7
- Driver or Module: 
- Database type and version:  Mysql
- PHP version:  8.2.16
- Platform:  Windows

* [ ] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / [master](https://github.com/ADOdb/ADOdb/tree/master) branch / latest [hotfix](https://github.com/ADOdb/ADOdb/branches/all?query=hotfix) branch  
  ⚠️ Keep only the applicable option(s), i.e. where you actually tested, and remove the others

### Steps to reproduce
**Detailed, step-by-step instructions to reproduce the behavior, including:
//
// ADODB
//
require_once("adodb/adodb.inc.php");

$GDA = NewADOConnection($CONFIG_db_Engin);  // mysqli

$GDA->PConnect($CONFIG_db_hostname, $CONFIG_db_username, $CONFIG_db_password, $CONFIG_db_database);
$GDA->SetFetchMode(ADODB_FETCH_ASSOC);
if($CONFIG_db_charset == "UTF-8") $GDA->EXECUTE("set names 'utf8'");

$GDA->Execute("set session sql_mode=''");

CleanAllRequest();**

### Additional context 
Add any other information relevant to the problem here.

I get this error message when starting my code : Fatal error: Uncaught Error: Call to undefined function mysqli_report() in C:\MesProjets\Profileur2\siteweb\adodb\drivers\adodb-mysqli.inc.php:104 Stack trace: #0 C:\MesProjets\Profileur2\siteweb\adodb\adodb.inc.php(5684): ADODB_mysqli->__construct() #1 C:\MesProjets\Profileur2\siteweb\adodb\adodb.inc.php(5518): ADONewConnection('mysqli') #2 C:\MesProjets\Profileur2\siteweb\inc\localhost.php(31): NewADOConnection('mysqli') #3 C:\MesProjets\Profileur2\siteweb\index.php(5): require_once('C:\\MesProjets\\P...') #4 {main} thrown in C:\MesProjets\Profileur2\siteweb\adodb\drivers\adodb-mysqli.inc.php on line 104

**Comment by dregad** [comment] 2024-08-06 17:11
Duplicate of #1040

**Closed** 2024-08-06 17:11 UTC
Labels: duplicate
