### ISSUE TITLE
adodb.org changes

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#574] opened 2019-12-31 03:40 UTC
@mnewnham What happened to the CSV driver on the wiki? It was removed from the _feature comparison matrix https://adodb.org/dokuwiki/doku.php?id=v5:database:feature_comparison without comment ..

**Comment by mnewnham** [comment] 2019-12-31 22:01
The CSV driver was just a duplicate of **proxy**,  which is the one being maintained (for the moment). Also there wasn't any feature in it, to be honest.

**Comment by peterdd** [comment] 2020-01-01 05:57
Thx.

I have another question:

There seems to be some URL inconsistency in documenation between the ADORecordSet methods move(), moveFirst(), moveNext(), and moveLast()

https://adodb.org/dokuwiki/doku.php?id=v5:reference:recordset:move
https://adodb.org/dokuwiki/doku.php?id=v5:reference:recordset:movefirst
https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:movenext
https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:movelast

Stumbled over it when trying to review/fix the copy-paste errors of the moveFirst() wiki page.

OFFTOPIC: Happy New Year!

**Comment by dregad** [comment] 2020-01-02 11:08
@peterdd Thanks, and best wishes to you too.

I fixed the documentation issue (see #577). Based on Mark's earlier reply, I see no reason to keep this thread open.

**Closed by dregad** 2020-01-02 11:08 UTC
Labels: documentation, no change required
