### ISSUE TITLE
PHP 8.1 : PHP Deprecated:  str_replace()

### ISSUE THREAD

**Issue by fluchette** [ADOdb/ADOdb#831] opened 2022-04-15 09:45 UTC
Hi,

I get the following message in PHP 8.1 (insert in DB) :

PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type
array|string is deprecated in adodb.inc.php on line 3476

Thanks

**Comment by dregad** [comment] 2022-04-16 09:07
This function expects a string. Can you please provide some context so I understand why it's getting _null_ instead of an empty string ?

**Comment by fluchette** [comment] 2022-04-19 09:11
Use 'quote' function in SQL insert command. Quote on empty string.

**Comment by dregad** [comment] 2022-05-06 22:45
> Quote on empty string.

@fluchette can you please be more specific, i.e. provide a code snippet that reproduces the error and also indicate which driver(s) you are using ?

I cannot get ADOConnection::quote() to throw a warning when called with an empty string `''` (tried pgsql, mysql, mssql drivers). I do get the error if I call it with `null`, but as mentioned before the function expects a _string_ argument, so IMO the current behavior is normal.

While it would be simple enough to fix the issue by casting the parameter to string prior to calling str_replace(), considering that in the future we'll be adding type declaration to ADOdb's functions, before implementing that I would like to understand your use case.

**Comment by dregad** [comment] 2022-05-13 16:54
Without feedback from you, and considering that I'm not able to reproduce the problem under normal usage conditions and that we're planning to add strong typing to function signatures, IMO it does not makes sense to implement a fix for this now.

**Closed by dregad** 2022-05-13 16:54 UTC
Labels: wontfix, PHP8.1

**Comment by dregad** [comment] 2022-06-08 09:34
For the record, attached is a tentative, not fully tested patch which was developed before the decision not to fix this issue was taken.

[0001-Fix-deprecated-warning-on-str_replace.txt](https://github.com/ADOdb/ADOdb/files/8860326/0001-Fix-deprecated-warning-on-str_replace.txt)
