### ISSUE TITLE
Warning: mysqli_free_result(): Couldn't fetch mysqli_result is shown in function _close for empty mysqli_result

### ISSUE THREAD

**Issue by aga112b** [ADOdb/ADOdb#491] opened 2019-02-15 13:05 UTC
Hi,
Unfortunately solution added by ivanbogomoloff in issue #463 causes that there is displayed warning:
`Warning: mysqli_free_result(): Couldn't fetch mysqli_result`
when the function ADORecordSet_mysqli->_close( ) is run.
I don't know why in function `_close`, `$this->_queryID` is instance of mysqli_result but couldn't be fetched. I found out that warning occurs when mysqli_result is empty (when I cast it to array and var_dump it looks:

```
array (size=5)
  'current_field' => null
  'field_count' => null
  'lengths' => null
  'num_rows' => null
  'type' => null
```
I've tried to find solution how to change mentioned code to not caused warnings but still resolve problem with displaying error

```
'LOGSQL Insert Failed: insert into adodb_logsql (created,sql0,sql1,params,tracer,timer) values( NOW(),?,?,?,?,?)
Commands out of sync; you can't run this command now'.
```
I found out that if in adodb-mysqli.inc.php in function `_close` we use
`if($this->_queryID instanceof mysqli_result && (!empty(implode('',(array)$this->_queryID)))) {`
instead
`if($this->_queryID instanceof mysqli_result) {`
then warning will not be displayed.

**Comment by dregad** [comment] 2019-03-04 11:56
@aga112b could you please provide a code snippet to reproduce the problem ?

**Comment by aga112b** [comment] 2019-03-06 14:39
when you set `$ADODB_PERF_MIN` to `0.0001`
and run code:
```
$sql = 'SELECT * FROM table ORDER BY name ASC, id ASC';
$result_array = $db->SelectLimit($sql, 1);
$result_array = $result_array->FetchRow();
```
where `$db` is a instance of `ADODB_mysqli`
then you should see warning 
`Warning: mysqli_free_result(): Couldn't fetch mysqli_result`

**Comment by dregad** [comment] 2020-01-04 17:04
Sorry, but I'm not able to reproduce the error with the provided information.

I'll close this and the associated PR #494 for now, but feel free to reopen if the problem persists and you can provide additional input.

**Closed by dregad** 2020-01-04 17:04 UTC
Labels: mysql, not reproducible

**Comment by dolphinotaku** [comment] 2020-06-17 17:42
Hi,
I have the same issue. it is weird, it was not happening every time, 3 times throw warning out of 10 F5 

Error:
<b>Warning</b>:  mysqli_free_result() expects parameter 1 to be mysqli_result, bool given in <b>D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb-perf.inc.php</b> on line <b>170</b><br />

my working env.:
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6
sqlsrv ExtensionVer | 5.8.0+12928
ADOdb Version: v5.20.17  31-Mar-2020

no error details printed even I updated the "adodb-perf.inc.php" as below
```
            try{
                if($conn instanceof ADODB_mysqli && $conn->_queryID) {
                    mysqli_free_result($conn->_queryID);
                }
                $ok = $conn->Execute($isql,$arr);
            }catch(Exception $e) {
                print_r($e->getTraceAsString());
                error_log("Error message:\n"+$e->getTraceAsString(), 3, "C:/php.log");
            } catch(Error $e) {
                var_dump($e->getTrace());
                error_log("Error message:\n"+$e->getTrace(), 3, "C:/php.log");
            }
```

coz the error/warning will break the JSON response, I temporary set display_errors = Off in php.ini to ignore the errors, any ideas? please advise.

**Comment by dolphinotaku** [comment] 2020-10-16 13:09
the error throws on ADORecordSet_mysqli->_close()
```
WarningWithStacktrace: mysqli_free_result(): Couldn't fetch mysqli_result in D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1067
Stack trace:
#0 [internal function]: exception_error_handler(2, 'mysqli_free_res...', 'D:\\xampp\\htdocs...', 1067, Array)
#1 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(1067): mysqli_free_result(Object(mysqli_result))
#2 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php(4037): ADORecordSet_mysqli->_close()
#3 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php(3353): ADORecordSet->Close()
#4 D:\xampp\htdocs\yoga\Controller\yi23packageprice.php(109): ADORecordSet->__destruct()
#5 D:\xampp\htdocs\yoga\Controller\yi23packageprice.php(28): Controller\yi23packageprice->FindData(Object(stdClass))
#6 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(253): Controller\yi23packageprice->InquiryData(Object(stdClass))
#7 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(103): ConnectionManager->ExecuteProgramMethod(Object(Controller\yi23packageprice), 'InquiryData')
#8 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(314): ConnectionManager->Initialize()
#9 {main}
```

**Comment by dolphinotaku** [comment] 2020-10-16 13:33
the one I know was if switching the pages to call adodb frequently could produce the error
```
WarningWithStacktrace: mysqli_fetch_array(): Couldn't fetch mysqli_result in D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1049
Stack trace:
#0 [internal function]: exception_error_handler(2, 'mysqli_fetch_ar...', 'D:\\xampp\\htdocs...', 1049, Array)
#1 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(1049): mysqli_fetch_array(Object(mysqli_result), 1)
#2 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php(3794): ADORecordSet_mysqli->_fetch()
#3 D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php(890): ADORecordSet->FetchRow()
#4 D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php(616): Core\Database\DatabaseMysqlConnector->ConvertADORecordSetToResultSet(Object(ADORecordSet_mysqli))
#5 D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php(154): Core\Database\DatabaseMysqlConnector->QueryExecute('SELECT \r\n\t\t\t`CO...')
#6 D:\xampp\htdocs\yoga\Core\Database\DatabaseFactory.php(68): Core\Database\DatabaseMysqlConnector->QueryKeySchema()
#7 D:\xampp\htdocs\yoga\Core\Database\DatabaseFactory.php(42): Core\Database\DatabaseFactory->CreateKeyIndexSchema()
#8 D:\xampp\htdocs\yoga\Core\Database\DatabaseManager.php(9): Core\Database\DatabaseFactory->__construct()
#9 D:\xampp\htdocs\yoga\Model\YogaTeacherManager.php(16): Core\Database\DatabaseManager->__construct()
#10 D:\xampp\htdocs\yoga\Controller\ye10teacher.php(13): Model\YogaTeacherManager->__construct()
#11 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(251): Controller\ye10teacher->GetTableStructure(Object(stdClass))
#12 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(101): ConnectionManager->ExecuteProgramMethod(Object(Controller\ye10teacher), 'GetTableStructu...')
#13 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(312): ConnectionManager->Initialize()
#14 {main}


WarningWithStacktrace: mysqli_free_result(): Couldn't fetch mysqli_result in D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1067
Stack trace:
#0 [internal function]: exception_error_handler(2, 'mysqli_free_res...', 'D:\\xampp\\htdocs...', 1067, Array)
#1 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(1067): mysqli_free_result(Object(mysqli_result))
#2 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php(4037): ADORecordSet_mysqli->_close()
#3 D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php(3353): ADORecordSet->Close()
#4 D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php(154): ADORecordSet->__destruct()
#5 D:\xampp\htdocs\yoga\Core\Database\DatabaseFactory.php(68): Core\Database\DatabaseMysqlConnector->QueryKeySchema()
#6 D:\xampp\htdocs\yoga\Core\Database\DatabaseFactory.php(42): Core\Database\DatabaseFactory->CreateKeyIndexSchema()
#7 D:\xampp\htdocs\yoga\Core\Database\DatabaseManager.php(9): Core\Database\DatabaseFactory->__construct()
#8 D:\xampp\htdocs\yoga\Model\YogaTeacherManager.php(16): Core\Database\DatabaseManager->__construct()
#9 D:\xampp\htdocs\yoga\Controller\ye10teacher.php(13): Model\YogaTeacherManager->__construct()
#10 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(251): Controller\ye10teacher->GetTableStructure(Object(stdClass))
#11 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(101): ConnectionManager->ExecuteProgramMethod(Object(Controller\ye10teacher), 'GetTableStructu...')
#12 D:\xampp\htdocs\yoga\Core\core.connection.manager.php(312): ConnectionManager->Initialize()
#13 {main}
```

**Comment by dolphinotaku** [comment] 2020-10-16 15:28
final, I found the reason. coz I always calling ADORecordSet_mysqli->fetchRow() in the code
ever the SQL execution was failed. Kindly note the return result may be false, empty array, array or a ADORecordSet_mysqli instance depending on the condition

```
// for $dbinstance->SelectLimit
// SelectLimit() returns the ADORecordSet_mysqli
//  or false if the statement execution fails. 
// https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:selectlimit&s[]=selectlimit

// for $dbinstance->GetAll()
// GetAll() returns a the entire recordSet in an array
//  or false if the statement execution fails. 
// If no records match the provided SQL statement, an empty array is returned. 
// https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getall

// for $dbinstance->GetRow()
// GetRow() Executes the SQL and returns the first tuple of the data set
//  or false if the statement execution fails. 
// If no records match the provided SQL statement, an empty array is returned.
// https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getrow

// for $dbinstance->GetOne()
// Executes the SQL and returns the first column of the first row
// GetOne() Executes the SQL and returns the first column of the first tuple of the data set
// If an error occurs, either false or null is returned depending on the value of $ADODB_GETONE_EOF. 
// https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:getone
```

**Comment by dolphinotaku** [comment] 2020-10-26 13:08
unfortunately, the problem still appears intermittent on the same PHP page.
i use below code to price trace

```
Class WarningWithStacktrace extends ErrorException {}
function exception_error_handler($severity, $message, $file, $line) {
    debug_print_backtrace();
    if ((error_reporting() & $severity)) {
        if ($severity & (E_WARNING | E_NOTICE | E_USER_WARNING | E_USER_NOTICE)) {
            $ex = new WarningWithStacktrace($message, 0, $severity, $file, $line);
            echo "\n" . $ex . "\n\n";
            return true;
        } else {
            throw new ErrorException($message, 0, $severity, $file, $line);
        }
    }
}
set_error_handler("exception_error_handler");
```

the error log shows below,
I checked the select statement is fine if I run on phpmyadmin
```
#0  exception_error_handler(2, mysqli_fetch_array(): Couldn't fetch mysqli_result, D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php, 1037, Array ())
#1  mysqli_fetch_array(mysqli_result Object ([current_field] => ,[field_count] => ,[lengths] => ,[num_rows] => ,[type] => ), 1) called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1037]
#2  ADORecordSet_mysqli->MoveNext() called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:3519]
#3  ADORecordSet->GetArray() called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:1817]
#4  ADOConnection->GetArray(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC, ) called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:1641]
#5  ADOConnection->GetAll(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC) called at [D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php:367]
#6  Core\Database\DatabaseMysqlConnector->selectAll(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC) called at [D:\xampp\htdocs\yoga\Controller\yi31article.php:76]
#7  Controller\yi31article->FindData(stdClass Object ([Action] => InquiryData,[Table] => yi31article,[InquiryCriteria] => stdClass Object ([PageNum] => 1,[Status] => %,[ArticleType] => %,[RetrieveRecordsLimit] => 10),[InquiryRecord] => stdClass Object ())) called at [D:\xampp\htdocs\yoga\Controller\yi31article.php:26]
#8  Controller\yi31article->InquiryData(stdClass Object ([Action] => InquiryData,[Table] => yi31article,[InquiryCriteria] => stdClass Object ([PageNum] => 1,[Status] => %,[ArticleType] => %,[RetrieveRecordsLimit] => 10),[InquiryRecord] => stdClass Object ())) called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:247]
#9  ConnectionManager->ExecuteProgramMethod(Controller\yi31article Object (), InquiryData) called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:97]
#10 ConnectionManager->Initialize() called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:308]

#0  exception_error_handler(2, mysqli_free_result(): Couldn't fetch mysqli_result, D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php, 1066, Array ())
#1  mysqli_free_result(mysqli_result Object ([current_field] => ,[field_count] => ,[lengths] => ,[num_rows] => ,[type] => )) called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:1066]
#2  ADORecordSet_mysqli->_close() called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:4037]
#3  ADORecordSet->Close() called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:1818]
#4  ADOConnection->GetArray(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC, ) called at [D:\xampp\htdocs\yoga\vendor\adodb\adodb-php\adodb.inc.php:1641]
#5  ADOConnection->GetAll(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC) called at [D:\xampp\htdocs\yoga\Core\Database\DatabaseMysqlConnector.php:367]
#6  Core\Database\DatabaseMysqlConnector->selectAll(
			SELECT 
			content.*, lang.IETF_BCP_47, lang.EnglishName
			FROM
			`article_content` content, `article_language` lang
            WHERE
            content.LanguageID = lang.MYUID
			AND content.MarkedDelete <> 'Y'
			AND lang.MarkedDelete <> 'Y'
			ORDER BY 
			content.LanguageID ASC) called at [D:\xampp\htdocs\yoga\Controller\yi31article.php:76]
#7  Controller\yi31article->FindData(stdClass Object ([Action] => InquiryData,[Table] => yi31article,[InquiryCriteria] => stdClass Object ([PageNum] => 1,[Status] => %,[ArticleType] => %,[RetrieveRecordsLimit] => 10),[InquiryRecord] => stdClass Object ())) called at [D:\xampp\htdocs\yoga\Controller\yi31article.php:26]
#8  Controller\yi31article->InquiryData(stdClass Object ([Action] => InquiryData,[Table] => yi31article,[InquiryCriteria] => stdClass Object ([PageNum] => 1,[Status] => %,[ArticleType] => %,[RetrieveRecordsLimit] => 10),[InquiryRecord] => stdClass Object ())) called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:247]
#9  ConnectionManager->ExecuteProgramMethod(Controller\yi31article Object (), InquiryData) called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:97]
#10 ConnectionManager->Initialize() called at [D:\xampp\htdocs\yoga\Core\core.connection.manager.php:308]
```

it makes me hard to guess where is the problem, I uploaded my code in [https://github.com/dolphinotaku/Yogalogy_Studio_Site](https://github.com/dolphinotaku/Yogalogy_Studio_Site), 
the test case is sending HTTP request JSON in POST to Core/core.connection.manager.php
```
{"Action":"InquiryData","Table":"yi31article","InquiryCriteria":{"PageNum":1,"Status":"%","ArticleType":"%","RetrieveRecordsLimit":10},"InquiryRecord":{}}
```
hope someone could help or advise.
