### ISSUE TITLE
Broken _Execute function

### ISSUE THREAD

**Issue by CreatrixTeam** [ADOdb/ADOdb#119] opened 2015-06-15 19:52 UTC
The commit "https://github.com/ADOdb/ADOdb/commit/41839f5c18abe262ee088f1d4bd92453616d2a4a" broke the behavior of the _Execute function, atleast with the odbc mssql driver. The $sql variable can be an array that contain other variables beside strings. The function "adodb_strip_count_keyword" forces all values to be converted to strings, breaking behavior. The culprit is the following line in _Execute which was added in the afore mentioned commit:

$sql = $this->adodb_strip_count_keyword( $sql );

Essentially, the code must remember that we could have prepared statements. This means the above line is called too late. The error in our case is caused by the above code converting a resource into a string, breaking calls to odbc_execute in the function _query in the file "adodb-odbc.inc.php"

Note: This appears related to https://github.com/ADOdb/ADOdb/issues/105 as well.

**Comment by ipso** [comment] 2015-06-15 23:16
Code has already been submitted to fix #105 and it should fix your issue as well. Just waiting for dregad to merge the fix.

**Comment by dregad** [comment] 2015-08-04 12:30
Closing this as duplicate of #105 - proposed fix in #109

**Closed by dregad** 2015-08-04 12:30 UTC
Labels: duplicate
