### ISSUE TITLE
Notice: Object of class mysqli_result could not be converted to int

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#873] opened 2022-09-10 16:13 UTC
Notice: Object of class mysqli_result could not be converted to int in vendor\adodb\adodb-php\adodb.inc.php on line 3946

Hello, 
This message started showing after moving from 5.21.4 to the latest 5.22

I am running php8.1

**Comment by dregad** [comment] 2022-09-10 18:05
Duplicate of #867

**Closed** 2022-09-10 18:05 UTC
Labels: duplicate
