### ISSUE TITLE
Set UTF-8  to adodb connection using Firebird Database

### ISSUE THREAD

**Issue by Gabrielr47** [ADOdb/ADOdb#266] opened 2016-08-05 20:25 UTC
**Firebird**

I'm trying to set charset utf-8 in my adodb config files but the charset not work, I was searching for some answer and people said that adodb can't be set charset if the charset in db is none.

I can't set the charset to utf8 in db. it's possible set in adodb?

In the case, how can i force adodb conversion charset none to utf8 ?

**Platform:**
	        Windows 10 Pro + Apache 2.4 and PHP 5.6.9
**Database:**
	       Firebird
**Version of ADOdb:**
	       Current Production version 5.20.4
**Code Snippet:**
```

require('/adodb5/adodb.inc.php');

$username = 'SYSDBA';
$password = 'masterkey';

$db = ADONewConnection('firebird');
$db->debug = true;
$db->dialect = 3;
$db->charSet = 'UTF8';
$db->Connect('localhost:C:\foo.FDB', $username, $password) or die("Falha na Conexão ao banco de dados: " . $db->ErrorMsg());
$db->SetFetchMode(ADODB_FETCH_ASSOC);

$sql = 'select * from users';

if (!($result = $db->Execute($sql))):
   throw new Exception($db->ErrorMsg());
elseif ($result->RecordCount() > 0):
   var_dump($result->_array);
endif;
```

I try the SetCharSet too.

**Comment by mnewnham** [comment] 2016-08-06 19:50
Code you provide the following information please:

- Platform
- Database
- Version of ADOdb
- A Code Snippet as to how you are trying to connect and set the charset

**Comment by mnewnham** [comment] 2016-08-13 17:21
I believe you can just change your connect statement to 

`localhost:C:\foo.FDB';charset=utf8`

**Comment by Gabrielr47** [comment] 2016-08-16 13:51
It's does not work too.

**Comment by mnewnham** [comment] 2016-08-19 00:49
Having re-read your initial comment, I realize that you are unable to set the character set when directly connecting via PHP. Because ADOdb is layered on top of the standard PHP connection, you will have no better luck setting it from ADOdb. This is an issue you need to resolve at the DBMS level, I think

**Comment by dregad** [comment] 2016-09-14 15:48
@Gabrielr47 without feedback from you following @mnewnham latest comment, I'm closing this issue as not reproducible; feel free to reopen it if you can provide additional information that could help us diagnose the problem.

**Closed by dregad** 2016-09-14 15:48 UTC
Labels: firebird, not reproducible
