### ISSUE TITLE
Problem with "Prepare" and oci8 (Oracle)

### ISSUE THREAD

**Issue by sondek** [ADOdb/ADOdb#318] opened 2017-03-20 12:11 UTC
Hi,

recently I wanted to upgrade my ADOdb to the latest version (I used 5.11 before), but found out, that there seems to be a bug with the Prepare function using oci8. It works until 5.19, but all version greater than 5.20 have the same buggy behaviour.
I prepare an sql statement with two parameters. I set one of these parameters to a specific value before a loop, the other one is set in a while loop which loops through a different sql query. The first resultset of this loop is always correct, but ADOdb somehow looses the resource object in the second cycle. I receive an error:

Warning: oci_execute(): 22 is not a valid oci8 statement resource in /door/www-dev/www-root/libs/adodb/drivers/adodb-oci8.inc.php on line 1300
ADOConnection._Execute(Array[4], false) % line 1010, file: adodb-oci8.inc.php
ADODB_oci8.Execute(Array[4]) % line  110, file: su_db_tests.php
Fatal error: Call to a member function RecordCount() on a non-object in /door/www-dev/www-root/door/su_db_tests.php on line 112
(line 110 is the one: $devices=$conn->Execute($dev_stmt);, see below)

When I use older ADOdb version, it works and loops through all resultsets. In debug mode you see, that the oci8 ressource is always the same in ADOdb 5.19 or less, but from 5.20 it is gone after the first loop cycle.

I tried to prepare a demo for you:
First create three tables with some rows (just oracle sqplus statements):

```
create table devices_types (
type char(1),
longtype varchar2(64));

insert into devices_types (type, longtype) values('D', 'Detectors');
insert into devices_types (type, longtype) values('E', 'Equipment');
insert into devices_types (type, longtype) values('P', 'Pool devices');

commit;

create table devices (
deviceid number(8),
name varchar2(256),
type char(1));

insert into devices (deviceid, name, type) values (1, 'Det1', 'D');
insert into devices (deviceid, name, type) values (2, 'Det2', 'D');
insert into devices (deviceid, name, type) values (3, 'Det3', 'D');

insert into devices (deviceid, name, type) values (4, 'Equip4', 'E');
insert into devices (deviceid, name, type) values (5, 'Equip5', 'E');
insert into devices (deviceid, name, type) values (6, 'Equip6', 'E');

insert into devices (deviceid, name, type) values (7, 'Pool7', 'P');
insert into devices (deviceid, name, type) values (8, 'Pool8', 'P');
insert into devices (deviceid, name, type) values (9, 'Pool9', 'P');

create table setups_devices (
setupid number(8),
deviceid number(8));

insert into setups_devices (setupid, deviceid) values (12, 1);
insert into setups_devices (setupid, deviceid) values (12, 2);
insert into setups_devices (setupid, deviceid) values (12, 5);
insert into setups_devices (setupid, deviceid) values (12, 6);
insert into setups_devices (setupid, deviceid) values (12, 7);
insert into setups_devices (setupid, deviceid) values (12, 8);
insert into setups_devices (setupid, deviceid) values (12, 9);

commit;
```
check the tables with the query:
```
select d.name, dt.longtype from devices d
inner join devices_types dt on dt.type=d.type
inner join setups_devices sd on sd.deviceid=d.deviceid and sd.setupid=12
where d.type='E';
```
and now the php code:
```
$conn = NewADOConnection("oci8");
$conn->Connect(false, $dbuser, $dbpass, $dbtnsname);

$dev_prep ="select d.name, dt.longtype from devices d ";
$dev_prep.="inner join devices_types dt on dt.type=d.type ";
$dev_prep.="inner join setups_devices sd on sd.deviceid=d.deviceid and sd.setupid=:0 ";
$dev_prep.="where d.type=:1";

$dev_stmt=$conn->Prepare($dev_prep);

$conn->Bind($dev_stmt, $p0);
$conn->Bind($dev_stmt, $p1);

$p0=12;

$types=$conn->Execute("select type, longtype from devices_types");
$conn->debug=true;
while(!$types->EOF)
{
	$p1=$types->fields["TYPE"];
	$devices=$conn->Execute($dev_stmt);
	
	$row_count=$devices->RecordCount();
	
	echo $row_count;
	/*
	while(!$devices->EOF)
	{
		echo $devices->fields["LONGTYPE"].": ".$devices->fields["NAME"]."<br />";
		$devices->MoveNext();
	}
	*/
	$types->MoveNext();
}
```

I hope this is all you need to fix this issue.

Thank you.

Best regards,
Sondek

**Comment by dregad** [comment] 2017-03-21 10:07
Thanks for the detailed bug report, especially providing the steps to reproduce it. I will look into this as time allows.

**Comment by AndLindemann** [comment] 2017-07-20 12:52
We've encountered an issue which is probably caused by the same bug as well.
If you store a prepared statement in a static class variable, the resource will be lost after the first use of that variable. This was working with adodb versions older than 5.20, but since we upgraded to 5.20.9 we had to rewrite our scripts.

Additionally, just today we were hit by this again but without using a static variable. What I saw today was more like the issue Sondek described, where the resource gets lost somewhere while looping through data to be processed.

There definitely is an issue with prepared statements and oci8 somewhere. That was fine with the versions before 5.20 but since 5.20, using prepared statements seems to hold many risks if you try and pass them through loops or statics or anywhere across function boundaries.

**Comment by mnewnham** [comment] 2017-08-10 23:16
This has not been forgotten....

I've been spending some time on code analysis, and whilst I can definitely agree that it used to work at 5.19 and now doesn't, I cannot work out how this ever worked, given that some of the variables used seem to be at the connection level, rather than recordset. Luck maybe? I'll continue to look at this.

**Comment by mnewnham** [comment] 2017-08-13 22:41
The answer is in the __destruct() method of ADOrecordset in the core adodb.inc.php.

Simply remarking the method out solves the problem, but at this stage, I do not know:

- Why it solves the ptoblem
- Why the __destruct method was added or the ramifications or removing it again @dregad , any ideas?

**Comment by dregad** [comment] 2017-08-14 09:36
@mnewnham the destructor was added as a fix for #143. This was a contribution from the community, which tbh I merged without in-depth testing on all drivers. 

ADORecordSet::Close() calls the specific <driver>::_close() method, and in the case of oci8 that calls oci_free_statement(), which is probably what is causing the problem (didn't test to confirm).

Not sure how how we could fix this without breaking #143

**Comment by colinmo** [comment] 2018-04-16 05:24
If this is an oci8 specific issue with oci_free_statement, then is it possible to just only call $this->Close() if $this->databaseType != "oci8" ?  I've just executed this on my local install using oci8 and it works a treat. Havent' tested against other drivers.

Happy to submit pull request if that's feasible.

**Comment by colinmo** [comment] 2018-04-16 05:31
Or, engaging brain here, using the ADORecordset_oci8 extension of ADORecordSet to overrule the __destruct() method with no close? Means no if statement, so faster.

**Comment by colinmo** [comment] 2018-04-16 05:36
I'd like to suggest an alteration to drivers/adodb-oci8.inc.php (and other oci libs) to override the __destruct() method with {}, so it does not perform the close. Happy to submit a pull request if viewed appropriate.

**Closed** 2018-07-21 00:04 UTC
Labels: bug, oci8 (oracle)
