### ISSUE TITLE
possible bug with $ADODB_QUOTE_FIELDNAMES

### ISSUE THREAD

**Issue by rgreenwood** [ADOdb/ADOdb#572] opened 2019-12-22 20:36 UTC
Not all of my fields are quoted in GetUpdateSQL() for example:
`$ADODB_QUOTE_FIELDNAMES = 'NATIVE';

$conn->GetUpdateSQL($rs, $dataArray, $where )
"UPDATE soils SET "zone"='1S', "HM%"='0.27', "W/V"='1.43', "CEC"='3.4', "BS%"='79', "Acidity"='0.7', "pH"='5.8', "P-I"='137', "K-I"='31', "Ca%"='64', "Mg%"='11', "Mn-AI"='107', "Zn-I"='74', "Cu-I"='78', "S-I"='53', ss = null, "complete_date"='2019-10-25', "Lab"='NCDA', "crop"='CORN', "Pneeds"=0, "KNeeds"=76, Needs S = null, "Needs Zn"='-', "Needs Cu"='-', "Needs Mn"='-', Needs Mg = null, Ca lb-ac = null, "Mg meq"=0, "Lime 6.0 lb"=350, "Lime 6.2 lb"=700, AMS = null, SOP = null, MOP = null, TSP = null, AMS sum = null, SOP sum = null, MOP sum = null, TSP sum = null, Lime sum = null, acres = null, "zones_ogc_fid"=17003, "rowdate"='2019-12-22', "pk"=8, "sample_year"=2020 WHERE  pk=8"`

The first ~15 column names are quoted, then columns names are randomly quoted and not. I'm using adodb -5.20.15 with a "postgres8" driver. My table definition:
```
CREATE TABLE work.soils (
       "zone" character varying(5) COLLATE pg_catalog."default",
	"HM%" character varying(10) COLLATE pg_catalog."default",
	"W/V" character varying(9) COLLATE pg_catalog."default",
	"CEC" character varying(15) COLLATE pg_catalog."default",
	"BS%" character varying(9) COLLATE pg_catalog."default",
	"Acidity" character varying(5) COLLATE pg_catalog."default",
	"pH" character varying(5) COLLATE pg_catalog."default",
	"P-I" character varying(5) COLLATE pg_catalog."default",
	"K-I" character varying(5) COLLATE pg_catalog."default",
	"Ca%" character varying(5) COLLATE pg_catalog."default",
	"Mg%" character varying(5) COLLATE pg_catalog."default",
	"Mn-AI" character varying(14) COLLATE pg_catalog."default",
	"Zn-I" character varying(12) COLLATE pg_catalog."default",
	"Cu-I" character varying(5) COLLATE pg_catalog."default",
	"S-I"  character varying(5) COLLATE pg_catalog."default",
	"ss"    text COLLATE pg_catalog."default",
	"complete_date" character varying(13) COLLATE pg_catalog."default",
	"Lab"   text COLLATE pg_catalog."default",
	"crop"    character varying(16) COLLATE pg_catalog."default",
	"Pneeds"   double precision,
	"KNeeds"   double precision,
	"Needs S"  character varying(3) COLLATE pg_catalog."default",
	"Needs Zn" character varying(3) COLLATE pg_catalog."default",
	"Needs Cu" character varying(3) COLLATE pg_catalog."default",
	"Needs Mn" character varying(3) COLLATE pg_catalog."default",
	"Needs Mg" character varying(3) COLLATE pg_catalog."default",
	"Ca lb-ac" double precision,
	"Mg meq"   double precision,
	"Lime 6.0 lb"   integer,
	"Lime 6.2 lb"    integer,
	"AMS" integer,
        "SOP" integer,
    "MOP" integer,
    "TSP" integer,
    "AMS sum" double precision,
    "SOP sum" double precision,
    "MOP sum" double precision,
    "TSP sum" double precision,
    "Lime sum" double precision,
    "acres" double precision,
    "zones_ogc_fid" integer,
    "rowdate" date DEFAULT now(),
    "pk" serial,
    "sample_year" integer,
    CONSTRAINT soils_pk PRIMARY KEY (pk)
)
```

**Comment by peterdd** [comment] 2019-12-23 03:13
I think the problem is the combination of table field names that contain spaces (or contains other characters that needs to be the field name quoted) and setting a null value there.

Wrote a little test script:
```php
<?php

include("../adodb.inc.php");

$pg_hostname='localhost';
$pg_user='adodb';
$pg_password='adodb';
$pg_database='adodbtest';

# example table based on adodb github issue 572
$pg_table='
CREATE TABLE soils (
        "crop" character varying(16) COLLATE pg_catalog."default",
        "KNeeds" double precision,
        "Needs S" character varying(3) COLLATE pg_catalog."default",
        "pk" serial,
        CONSTRAINT soils_pk PRIMARY KEY (pk)
)';

$db = ADONewConnection('postgres');

if ($db->connect($pg_hostname, $pg_user, $pg_password, $pg_database)){
        echo "getUpdateSQL() demo with postgresql:\n";
} else {
        echo "Couldn't connect to '$pg_hostname' database '$pg_database' with user '$pg_user' and password '$pg_password'";
}
$select='select * from soils where pk=8';
echo $select."\n\n";

$result=$db->execute($select);
#print_r($result);

$fields=array(
        'KNeeds'=>76,
        'Needs S' => null,
);

echo "        ".$db->getUpdateSQL($result, $fields)."\n";
echo "forced: ".$db->getUpdateSQL($result, $fields, true)."\n";
echo "\n\nWatch 'Kneeds' get uppercased, 'Needs S' not. And the field with space 'Needs S' misses required quoting.\n\n";

$ADODB_QUOTE_FIELDNAMES = 'NATIVE';
echo 'OK, now lets try with $ADODB_QUOTE_FIELDNAMES = \'NATIVE\''."\n\n";

echo "        ".$db->getUpdateSQL($result, $fields)."\n";
echo "forced: ".$db->getUpdateSQL($result, $fields, true)."\n\n";

echo 'Now trying with setting a string to the field with spaces \'Needs S\':'."\n\n";
$fields=array(
        'KNeeds' => 76,
        'Needs S' => 'bla',
);


echo "        ".$db->getUpdateSQL($result, $fields)."\n";
echo "forced: ".$db->getUpdateSQL($result, $fields, true)."\n\n";

echo 'Now try setting null to a field without spaces ..'."\n\n";

$fields=array(
        'KNeeds' => null,
        'Needs S' => 'bla',
);

echo "        ".$db->getUpdateSQL($result, $fields)."\n";
echo "forced: ".$db->getUpdateSQL($result, $fields, true)."\n\n";

?>
```

It produces something like this:

```
getUpdateSQL() demo with postgresql:
select * from soils where pk=8

        UPDATE soils SET KNEEDS=76 WHERE pk=8
forced: UPDATE soils SET KNEEDS=76, Needs S = null WHERE pk=8


Watch 'Kneeds' get uppercased, 'Needs S' not. And the field with space 'Needs S' misses required quoting.

OK, now lets try with $ADODB_QUOTE_FIELDNAMES = 'NATIVE'

        UPDATE soils SET "KNeeds"=76 WHERE pk=8
forced: UPDATE soils SET "KNeeds"=76, Needs S = null WHERE pk=8

Now trying with setting a string to the field with spaces 'Needs S':

        UPDATE soils SET "KNeeds"=76, "Needs S"='bla' WHERE pk=8
forced: UPDATE soils SET "KNeeds"=76, "Needs S"='bla' WHERE pk=8

Now try setting null to a field without spaces ..

        UPDATE soils SET "Needs S"='bla' WHERE pk=8
forced: UPDATE soils SET KNeeds = null, "Needs S"='bla' WHERE pk=8
```

As you can see from the output, field 'Needs S' is not quoted when the field value null should be set.

I changed 
```php
$setFields .= $field->name . " = null, ";
```

to 

```php
$setFields .= $fnameq . " = null, ";
```
in file adodb-lib.inc.php function _adodb_getupdatesql() - currently around line 736 in the ADOdb master branch - and now the test output looks much better:

```
getUpdateSQL() demo with postgresql:
select * from soils where pk=8

        UPDATE soils SET KNEEDS=76 WHERE pk=8
forced: UPDATE soils SET KNEEDS=76, "NEEDS S" = null WHERE pk=8


Watch 'Kneeds' get uppercased, 'Needs S' not. And the field with space 'Needs S' misses required quoting.

OK, now lets try with $ADODB_QUOTE_FIELDNAMES = 'NATIVE'

        UPDATE soils SET "KNeeds"=76 WHERE pk=8
forced: UPDATE soils SET "KNeeds"=76, "Needs S" = null WHERE pk=8

Now trying with setting a string to the field with spaces 'Needs S':

        UPDATE soils SET "KNeeds"=76, "Needs S"='bla' WHERE pk=8
forced: UPDATE soils SET "KNeeds"=76, "Needs S"='bla' WHERE pk=8

Now try setting null to a field without spaces ..

        UPDATE soils SET "Needs S"='bla' WHERE pk=8
forced: UPDATE soils SET "KNeeds" = null, "Needs S"='bla' WHERE pk=8
```

The function _adodb_getupdatesql() has terrible broken indentation and there are more places in that function that needs review if $fnameq should be used instead of $field->name .

**Comment by rgreenwood** [comment] 2019-12-23 17:49
Thanks so much for looking at this. I changed `$field->name` to `$fnameq` in both `case 1:` and `case 3:` in `_adodb_getupdatesql()` and my issue appears to be resolved. Also, my apologies for the terrible formatting of my original post.

**Comment by peterdd** [comment] 2019-12-26 06:09
This bug is not just pgsql-specific.

**Comment by mnewnham** [comment] 2019-12-27 18:22
But this is a common feeder function to all database drivers right? In fact as far as I can tell, Its only ever called from getUpdateSql(), so fixing this here will fix the issue for all drivers.

**Comment by peterdd** [comment] 2019-12-28 08:58
? Yes, that's why I made that comment and wondered why you added the pgsql label.

**Comment by mnewnham** [comment] 2019-12-29 01:08
I added the labels based on the original issue before I looked at the source. Would you have time to do a fix for this?

**Comment by peterdd** [comment] 2019-12-30 00:47
I try.

**Comment by peterdd** [comment] 2020-01-05 14:01
pr #585

**Closed** 2020-01-09 00:49 UTC
Labels: bug, core
