### ISSUE TITLE
Fatal error: Uncaught TypeError: ibase_num_fields()

### ISSUE THREAD

**Issue by hufex** [ADOdb/ADOdb#858] opened 2022-08-23 22:10 UTC
adodb/adodb-php: v5.22.2
php 8.0.22
LI-V6.3.9.27139 Firebird 2.5
Linux  3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    $conex = newAdoConnection('ibase');
    $conex->dialect = 3; 
    $conex->connect(DB_HOST . ":" . DB_NAME, DB_USER, DB_PASSWD);
    if(!$conex->isConnected()){
        var_dump($conex);
        exit(0);
    }    
    $conex->debug = true;
    $query  = "UPDATE casos set ENUNCIADO = '' where id_Caso = 1";
    $conex->execute($query);

`Fatal error: Uncaught TypeError: ibase_num_fields(): Argument #1 ($query_result) must be of type resource, int given in /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php:780 
Stack trace:
#0 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php(780): ibase_num_fields() 
#1 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(3961): ADORecordset_ibase->_initrs() 
#2 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(1590): ADORecordSet->Init() 
#3 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php(183): ADOConnection->_Execute() 
#4 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(1527): ADODB_ibase->_Execute() 
#5 /var/www/vhosts/httpdocs/pre/test.php(25): ADOConnection->Execute() 
#6 {main} 

Next TypeError: ibase_free_result(): Argument #1 ($result) must be of type resource, int given in /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php:853 
Stack trace:
#0 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php(853): ibase_free_result() 
#1 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(4671): ADORecordset_ibase->_close() 
#2 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(3941): ADORecordSet->Close() 
#3 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php(183): ADORecordSet->__destruct() 
#4 /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/adodb.inc.php(1527): ADODB_ibase->_Execute() 
#5 /var/www/vhosts/httpdocs/pre/test.php(25): ADOConnection->Execute() 
#6 {main} thrown in /var/www/vhosts/httpdocs/pre/vendor/adodb/adodb-php/drivers/adodb-ibase.inc.php on line 853`

**Comment by mnewnham** [comment] 2022-08-24 01:17
It would seem more likely that the errors are being triggered elsewhere in your code, because these errors are occurring when an attempt is made to instantiate a recordset on an invalid query. This would not happen on an **UPDATE** statement, but would happen on a **SELECT** statement or similar:

````php
$result = $db->execute("SELECT something FROM invalid_table");

$r = $result->fetchRow(); // <------- This statement generates the errors you describe
````

**Comment by dregad** [comment] 2022-08-25 14:53
I can reproduce this on PHP 8.0 and 8.1, same code on 7.4 works.

**Comment by mnewnham** [comment] 2022-08-25 20:08
PHP 8.1.9
Interbase driver: [php-8.1.3-interbase-1.1.1-linux-x64.so](https://github.com/FirebirdSQL/php-firebird/releases/download/v1.1.1/php-8.1.3-interbase-1.1.1-linux-x64.so)
Firebird Database 3.0

Using the "EMPLOYEES" demo database and the statement:

````php
UPDATE employee SET job_code = '' WHERE emp_no=1
````

This completes successfully. 

I am using a remote connection with a connect statement as follows:

````php
$db->connect('192.168.86.192:/var/lib/firebird/3.0/data/employee.fdb',"SYSDBA", "password")
````

### Possible Solution
I believe the problem you are having is related to a mismatch between the version of PHP (8.0, 8.1) and the version of Firebird database (2.5).  It would seem that in order to use PHP 8, you need to upgrade Firebird to 3,0 or higher. This issue is documented [here](https://stackoverflow.com/questions/63483052/php7-4-and-firebird-interbase-ibase-connect-ibase-query-call-to-undefined)

**Comment by dregad** [comment] 2022-08-26 13:00
> problem you are having is related to a mismatch between the version of PHP (8.0, 8.1) and the version of Firebird database (2.5)

I'm not so sure. The Firebird database on my dev box is definitely 3.0, and I confirmed that I do not have 2.5 installed.
```
$ firebird  -z
Firebird TCP/IP server version LI-V3.0.5.33220 Firebird 3.0
```
phpinfo() tells me the interbase extension version is 3.0.0 (that was installed with the standard Ubuntu package). I tried installing the latest driver from your link (1.1.1), but still get the same results, as reported by @hufex.

I believe the problem is caused by fbird_query() / ibase_query() returning the number of affected rows (see [PHP documentation][1])
_Note: In PHP 5.0.0 and up, this function will return the number of rows affected by the query for INSERT, UPDATE and DELETE statements. In order to retain backward compatibility, it will return true for these statements if the query succeeded without affecting any rows._

ADOConnection::_Execute() expects _true_ so instead of instantiating an ADORecordSet_empty object, it goes for a regular ADORecordset_ibase or ADORecordset_firebird, which chokes on PHP 8.x since the _queryID is an integer instead of a resource; PHP 7.4 allows this, but throws a warning but we suppress it with the @ operator.

I'll submit a pull request with a proposed fix for testing/review.

[1]: https://www.php.net/manual/en/function.ibase-query.php

**Comment by dregad** [comment] 2022-09-01 09:45
@hufex, @mnewnham  any comments or testing feedback on the proposed fix for this (pull request #860) ?

**Comment by mnewnham** [comment] 2022-09-03 21:53
Huh, thought I left a comment here, don't see it. Anyway. Do you think its worth saving off the last insert id and using it on insert_id() ?

**Comment by dregad** [comment] 2022-09-03 22:11
> Huh, thought I left a comment here, don't see it.

You mean this one -> https://github.com/ADOdb/ADOdb/pull/860#issuecomment-1234234965 ?

I answered there a few minutes ago.

**Closed** 2022-09-03 22:13 UTC
Labels: firebird, interbase, PHP8, PHP8.1
