### ISSUE TITLE
Deprecated - php 8.1

### ISSUE THREAD

**Issue by r23** [ADOdb/ADOdb#781] opened 2021-12-18 21:50 UTC
Hello,

thank you for maintaining this project for years.

When updating to PHP 8.1 in my xampp https://www.apachefriends.org/

Environment I get the following notices:

Deprecated:  Return type of ADODB_Iterator_empty::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3456

Deprecated:  Return type of ADODB_Iterator_empty::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3460

Deprecated:  Return type of ADODB_Iterator_empty::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3452

Deprecated:  Return type of ADODB_Iterator_empty::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3448

Deprecated:  Return type of ADODB_Iterator_empty::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3446

Deprecated:  Return type of ADORecordSet_empty::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3512

Deprecated:  Return type of ADODB_Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3584

Deprecated:  Return type of ADODB_Iterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3588

Deprecated:  Return type of ADODB_Iterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3580

Deprecated:  Return type of ADODB_Iterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3576

Deprecated:  Return type of ADODB_Iterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3572

Deprecated:  Return type of ADORecordSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~\adodb\adodb-php\adodb.inc.php on line 3672

Best regards

Ralf

**Comment by dregad** [comment] 2021-12-22 07:56
Duplicate of #771

**Closed by dregad** 2021-12-22 07:56 UTC
Labels: duplicate
