### ISSUE TITLE
Input array has x elements does not match

### ISSUE THREAD

**Issue by TestUserName213** [ADOdb/ADOdb#392] opened 2018-02-07 21:27 UTC
Hi,

I get the above error. 

The only thing I did was in function ADOLoadCode ($dbtype) I made a slight change to  
case 'postgres':
$class = $db = 'postgres8';

I switched this part to 
$class = $db = 'postgres64' as I need the 64 driver.

However sometimes I get an error on session update input array has x elements does not match....

So I looked into it and in function Execute in adodb.inc.php it tries to split the sql array
if (!is_array($sql) && !$this->_bindInputArray) {
				// @TODO this would consider a '?' within a string as a parameter...
			    $sqlarr = explode('?',$sql);

However my sql  is "UPDATE mike.sessions SET expiry = $1,expireref=$2 WHERE sesskey = $3 AND expiry >= $4 " and will not split it.

Am I misconfiguring this or I need to do something else as well ?

Thanks

**Comment by dregad** [comment] 2018-02-08 14:10
> The only thing I did was in function ADOLoadCode ($dbtype) I made a slight change to
case 'postgres':
$class = $db = 'postgres8';

That shouldn't be necessary, you can simply specify the individual driver you need when creating the connection

```
$db = ADONewConnection('postgres64');
```

> I need the 64 driver.

I'd be interested in knowing why, especially considering that it is deprecated and will be removed in a future version of ADOdb

As for your actual issue, could you please provide a code sample to reproduce the problem so I can get a better understanding of your issue ?

**Comment by mnewnham** [comment] 2018-02-08 23:48
Ah, that's an easy one to answer for us 'older' IT professionals. The postgres64 driver isn't a 64 bit implementation, it's for postgres version 6.4, which was end-of-life in 2003. 

Just use the  postgres9 driver for the most up to date connector

**Comment by dregad** [comment] 2018-03-06 12:01
@TestUserName213 since you did not provide any feedback, I'm closing this issue for now. Feel free to reopen with additional information.

**Closed by dregad** 2018-03-06 12:01 UTC
Labels: pgsql, question
