### ISSUE TITLE
deprected warnings using latest 5.22

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#861] opened 2022-08-28 17:34 UTC
Hello,

 I got this warnings while using the latest version with php 8.1 I set my php.ini
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off

runing on cli

Thank you

<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator_empty::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3149</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator_empty::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3153</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator_empty::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3145</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator_empty::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3141</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator_empty::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3139</b><br />
<br />
<b>Deprecated</b>:  Return type of ADORecordSet_empty::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3204</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3276</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3280</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3272</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3268</b><br />
<br />
<b>Deprecated</b>:  Return type of ADODB_Iterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3264</b><br />
<br />
<b>Deprecated</b>:  Return type of ADORecordSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/vendor/adodb/adodb-php/adodb.inc.php</b> on line <b>3356</b><br />

**Comment by dregad** [comment] 2022-08-30 12:05
@stccorp please make sure you are indeed using 5.22 - this problem has been fixed in ADOdb versions 5.20.21, 5.21.4 and 5.22.0.

I'm closing this as duplicate of #771

**Closed by dregad** 2022-08-30 12:05 UTC
Labels: duplicate
