### ISSUE TITLE
show Fatal error:

### ISSUE THREAD

**Issue by 81686372** [ADOdb/ADOdb#428] opened 2018-06-16 20:49 UTC
Fatal error: in E:\nginx\html\adodb\drivers\adodb-ado5.inc.php on line 94
![default](https://user-images.githubusercontent.com/39467313/41502315-d5bf109c-71e9-11e8-98ef-5d20e260aefe.png)

**Comment by dregad** [comment] 2018-06-17 09:19
The provided information is not sufficient to provide any help. Please specify ADOdb version, details about the environment and a code snippet to reproduce the problem.

For the record, as per [documentation](http://adodb.org/dokuwiki/doku.php?id=v5:database:ado), the ADO driver is obsolete and no longer supported; furthermore it cannot be used directly - you must use one of the child drivers.

**Comment by dregad** [comment] 2018-06-27 14:28
Closing the issue since you did not provide any feedback.

**Closed by dregad** 2018-06-27 14:28 UTC
