### ISSUE TITLE
Notice printed from MetaColumns() in adodb-mssqlnative line 757

### ISSUE THREAD

**Issue by eharris200** [ADOdb/ADOdb#289] opened 2016-11-09 03:36 UTC
Adodb 5.20.7 windows 7 sql server express version 11.0.60.20 php 7.0.11

Using parseschemafile() to parse xml data for table definition.  Then call executeSqlArray().  Table gets created but get notice:

PHP Notice:  Undefined property: ADODB_mssqlnative::$cachedSchemaFlush in C:\ine
tpub\wwwroot\adodb5\drivers\adodb-mssqlnative.inc.php on line 757

If I comment out:
//		if ($this->cachedSchemaFlush)
//			$cached_columns = array();
Notice goes away and tables are still created.  The user that is creating the tables was granted these permissions:

use master;
create login username with password = 'username';
create database usernamedb;
use usernamedb;
create user username for login username;
create schema usernamedb authorization username;
grant create table to username
alter user username with default_schema = usernamedb

**Comment by dregad** [comment] 2016-11-09 12:38
A code sample + xml data to reproduce the problem would be useful. Is this only with MSSQL, or can you reproduce this issue with other drivers as well ?

**Comment by eharris200** [comment] 2016-11-09 22:58
Not seeing this error in mysql 5.7 or oracle 12.1.0.2.  

require $WEBROOT . '/vendor/autoload.php';
include_once( $WEBROOT . "/adodb5/adodb.inc.php");
include $WEBROOT . '/adodb5/adodb-xmlschema03.inc.php';

$ADODB_DATE_LOCALE = ['d/m/Y','H:i:s'];
$db = newAdoConnection( "mssqlnative://username:password@localhost:1433/dbName" );
$db->setFetchMode( 2 );
$schema = new adoSchema( $db );
$dict = NewDataDictionary($db);
$sql = $schema->ParseSchemaFile( $argv[0] );
$result = $dict->executeSqlArray( $sql );  


[menu.txt](https://github.com/ADOdb/ADOdb/files/582093/menu.txt)

**Comment by dregad** [comment] 2016-11-19 23:51
Looks like the $cachedSchemaFlush property was added later (see commit 39e0c1dd2fe0476595a1ca2254bd255eb8476b47), in master branch only.

@mnewnham I'm not really sure what this property does (or is intended to do) - it is just set to *false*, and does not seem to be documented anywhere.

Anyway, to fix the issue, we can simply define the class variable.

**Comment by dregad** [comment] 2016-11-19 23:57
Fixed in 11cf505098ca9a7f2f6aa9effb3b9ad95ffb2766

**Closed by dregad** 2016-11-19 23:57 UTC
Labels: bug, mssql, xml schema

**Comment by mnewnham** [comment] 2016-11-22 00:11
Just as a side note, this crept in a while ago when i used my company's custom version of the driver to push some fixes. The purpose has been deprecated with the change to the way we load the metaschema when we initialize the connection. You can kill it we no harmful effects
