### ISSUE TITLE
[mysql] Custom mysql attributes of ADOFieldObject should be defined before use in metaColumns() method 

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#905] opened 2022-11-30 02:51 UTC
In PHP8.2, the method returns warnings because the attributes are not defined before use

````php
Deprecated: Creation of dynamic property ADOFieldObject::$scale is deprecated in drivers/adodb-mysqli.inc.php on line 946

Deprecated: Creation of dynamic property ADOFieldObject::$auto_increment is deprecated in drivers/adodb-mysqli.inc.php on line 967

Deprecated: Creation of dynamic property ADOFieldObject::$binary is deprecated in drivers/adodb-mysqli.inc.php on line 968

Deprecated: Creation of dynamic property ADOFieldObject::$unsigned is deprecated in drivers/adodb-mysqli.inc.php on line 969
````

**Comment by dregad** [comment] 2023-03-12 17:20
This is basically the same root cause as #906 and should be addressed by the same fix, so I'm closing this as duplicate.

**Closed by dregad** 2023-03-12 17:20 UTC
Labels: bug, mysqli, PHP8.2
