### ISSUE TITLE
adodb cache not working php8.1-fpm

### ISSUE THREAD

**Issue by lmramaya** [ADOdb/ADOdb#795] opened 2022-01-18 01:32 UTC
hello I hope you are very well when I configure my app to run in php8.1.1-fpm ubuntu 20.04 LTS and windows 10 the cache does not work and the following error:

/adodb/adodb-csvlib.inc.php:102 b5/adodb_b5b2885158fe0d1cc8fada4c80cc3eb7.cache): Failed to open stream: No such file or directory

works very well in php7.4.27-fpm ubuntu 20.0.4 LTS and windows 10.

thank you very much for the help you can give me

**Comment by mnewnham** [comment] 2022-01-18 02:44
1. Obvious first question: Does that file actually exist? I am asking it to determine if it is a write issue or read issue.
2. Is this the location that you expect the cache file to be located?
3. What version of ADOdb are you using?
4. What database are you using on the backend?
5. Can you try to run a query that accesses cache data from the command line? This is to eliminate the Apache-fpm module itself as a source of the problem
6. Could you enable ADOdb debugging `($db->debug=true`) and post the result of that please

**Comment by lmramaya** [comment] 2022-01-18 03:29
6. php7.4-fpm tmp/adodb/b1/adodb_b1760f33db11848611b1a45263dd1a03.cache cache failure: Timeout 0 (this is a notice and not an error)
5. nginx 1.18.0
4. mysql 8.0.27
3. adodb 5.21.3
1. and 2. drw-rw-r-x /tmp/adodb/

in php7.4 runs with notice in php8.1 the error is fatal

tks

**Comment by dregad** [comment] 2022-01-18 08:10
@mnewnham you tagged it with _memcache_ but considering the error message mentions a file `adodb_MD5.cache` I believe they are using ADODB_Cache_File, not ADODB_Cache_MemCache.

@lmramaya could you please provide a code snippet to reproduce the issue.

**Comment by mnewnham** [comment] 2022-01-18 13:42
We don't have a file cache tag, and it was late and instead of creating a new one I tagged it with the closest one available

**Comment by dregad** [comment] 2022-01-18 14:04
Fair enough... Maybe we should have a more general "cache" tag covering both features?

**Comment by lmramaya** [comment] 2022-01-18 16:12
in the File /adodb/adodb-csvlib.inc.php:102 

change:
$fp = @fopen($url,'rb');
for
$fp = file_exists($url);
if ($fp)
	$fp = @fopen($url,'rb');

and line 298
@unlink($filename);
for
if(file_exists($filename))
	@unlink($filename);

I don't know if it's the best solution but this way I solved the fatal one I'll check with more time if it works well for PHP8.0 and PHP8.1

tks

**Comment by mnewnham** [comment] 2022-01-19 02:01
I thini that this is a reasonable solution. This is likely a result of the change in PHP 8.0 where the @ symbol no longer silences fatal errors. The original design I suspect is to optimize speed by not checking for file existence first and using the file open failure as a signal that the file does not exist. Obviously we cannot do this now.

**Comment by dregad** [comment] 2022-01-19 07:55
I'm quite surprised that the @ operator on the fopen() call is not silencing the file not found error. PHP 8.0 only stopped suppressing _fatal_ errors, and [Documentation](https://www.php.net/manual/en/function.fopen.php#refsect1-function.fopen-errors) states this is a _warning_, not a fatal. A quick CLI test confirms successful suppression for me. 
```
$ php --version
PHP 8.1.1 (cli) (built: Dec 31 2021 07:26:20) (NTS)

$ php -a
php > $f = fopen('X', 'rb');
PHP Warning:  fopen(X): Failed to open stream: No such file or directory in php shell code on line 1

php > $f = @fopen('X', 'rb');
php > var_dump($f);
bool(false)
```

So while I'm fine with the proposed solution as well, I'd like to understand what is going on here. Maybe this is something specific to php-fpm or your environment ?

**Comment by lmramaya** [comment] 2022-01-19 15:49
development: windows 10 21H1 Apache 2.4 PHP/CLI 5.6 work, PHP/CLI 7.4.27 work PHP/CLI 8.0.12 not work PHP/CLI 8.1.1 not work

production: ubuntu 20.04.03 nginx 1.18.0 php5.6-fpm work php7.4-fpm work php8.1-fpm not work

tks

**Comment by dregad** [comment] 2022-01-19 16:03
@lmramaya as shown in my previous post, I'm not getting an error with `@fopen()` on PHP 8.1 with a non-existing file. Can you please provide a code snippet to reproduce the issue, as [requested previously](https://github.com/ADOdb/ADOdb/issues/795#issuecomment-1015162960). Thanks

**Comment by lmramaya** [comment] 2022-01-19 19:41
test php-cli 8.1.1
$fp = @fopen('C:/AppServ/www/tmp/adodb/af/adodb_afbdf16918ba4854cc66dec4ff5b5b29.cached','rb');
var_dump($fp);
result
bool(false)

If I delete all the temporary files in the adodb folder, my system not works and it is a fatal error.

FATAL [C:\AppServ\www\adodb\adodb-csvlib.inc.php:102] fopen(C:/AppServ/www/guarddog/tmp/adodb/af/adodb_afbdf16918ba4854cc66dec4ff5b5b29.cache): Failed to open stream: No such file or directory

removing the solution gives an error. active the solution works. I don't know what else to do to show the error sorry for the little information

**Comment by dregad** [comment] 2022-01-22 15:19
> test php-cli 8.1.1
> $fp = @fopen('C:/AppServ/www/tmp/adodb/af/adodb_afbdf16918ba4854cc66dec4ff5b5b29.cached','rb');
> var_dump($fp);
> result
> bool(false)

So you are not getting a fatal here, despite the fact that the file was not open successully since $fp is false.

It is not clear to me what you are doing next to get a fatal error (which despite my efforts I'm still unable to reproduced). 

This may be a red herring, but are you sure the path is correct ? In the error message it shows `www/guarddog/tmp`, while in the initial test it's just `www/tmp`... Still, it should not throw a fatal. There has to be something specific to your local environment that is causing this.

**Comment by mnewnham** [comment] 2022-01-22 16:22
I'm wondering if this is a filesystem or permissions issue. If the adodb cache directory is emptied, then adodb attempts to not only re-create the .cache file, but also the subdirectory that holds it. Maybe selinux is denying apache-fpm the right to create the files?

**Comment by dregad** [comment] 2022-01-23 10:56
I had a close look at the proposed fix, and I'm concerned that using file_exists() may introduce regressions because the function can't handle URLs and csv2rs() accepts either a file or an ftp/http URLs.

**Comment by dregad** [comment] 2022-02-11 12:40
@lmramaya since you have not answered my requests to provide a code snippet to reproduce the error, I'm going to close this issue. Feel free to reopen it when you're able to provide instructions to reproduce.

**Closed by dregad** 2022-02-11 12:40 UTC
Labels: bug, not reproducible, PHP8, caching, PHP8.1
