### ISSUE TITLE
[xmlschema] XMLSchema functions should support available encodings

### ISSUE THREAD

**Issue by ingyser** [ADOdb/ADOdb#898] opened 2022-11-10 11:49 UTC
Version: 5.22.4
Using extractSchema followed by parseSchemaString it throws an error:
`XML error: Invalid character at line XXX`
It happends if any data in any table has accent characters (á. é, í, ó, ú).
It can be solved replacing this (line 2184, file adodb-xmlschema03.inc.php):
```
if ( $val != htmlentities( $val ) ) {
	$row[$key] = '<![CDATA[' . $val . ']]>';
}
```
```
With this:
if ( !empty($val) && $val != htmlentities( $val ) ) {
	$row[$key] = '<![CDATA[' . utf8_encode($val) . ']]>';
}
```
(line 1798, file adodb-xmlschema03.inc.php):
```
xml_set_object( $xmlParser, $this );
```
With this:
```
xml_set_object( $xmlParser, $this );
xml_parser_set_option($xmlParser,XML_OPTION_TARGET_ENCODING, "ISO-8859-1");
```

**Comment by mnewnham** [comment] 2022-11-15 01:58
The XML Schema functions can support select encodings, default is UTF-8 The ability to use ISO-8859-1 and US-ASCII should be added

**Comment by mnewnham** [comment] 2022-11-19 18:21
#### Regarding the request to add utf8_encoding

[Per the PHP documentation](https://www.php.net/manual/en/function.utf8-encode.php), ``utf8_encode`` is now deprecated. In fact, utf_encode **only** works if the incoming date is ISO-8859-1 encoded. It's likely going to corrupt anything with a different character set.

#### Regarding ``xml_parser_set_option($xmlParser,XML_OPTION_TARGET_ENCODING, "ISO-8859-1"); ``
Again, this looks like a solution to a problem you are having that is going to break everybody elses use of the feature.

#### Summary

- I think that without major changes to the way this function uses encoding this change is going to break other people's usage of the system
- My feeling is that you have a problem with the encoding in your database that is the root cause of this requirement (for example, you've an old MySQL database with default latin encoding instead of utf-8)
- I'm putting a wontfix onto this.

**Closed by mnewnham** 2022-11-19 18:21 UTC
Labels: enhancement, wontfix, xml schema
