### ISSUE TITLE
Query fails in PageExecute() if SQL contains SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by mrdave1968** [ADOdb/ADOdb#845] opened 2022-06-24 13:39 UTC
If the sql string contains SQL_CALC_FOUND_ROWS, then PageExecute when executing the count(*) query fails, I resolved this with this code (could be done better I suppose):

```
function _adodb_getcount(&$zthis, $sql,$inputarr=false,$secs2cache=0)
{
	$qryRecs = 0;

+	$sql = str_replace('SQL_CALC_FOUND_ROWS', '', $sql);
...
```

**Comment by dregad** [comment] 2022-06-25 10:09
@mrdave1968 I am not able to reproduce this. Please provide additional information (ADOdb version, DB version, code snippet).

**Comment by dregad** [comment] 2022-06-25 10:14
And just for the record, per [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows) 
_The SQL_CALC_FOUND_ROWS query modifier and accompanying FOUND_ROWS function are deprecated as of MySQL 8.0.17_

**Comment by dregad** [comment] 2022-07-18 07:24
You have not provided any feedback, so I'm closing this issue. Feel free to reopen at a later time with the requested information.

**Closed by dregad** 2022-07-18 07:24 UTC
Labels: not reproducible, mysqli
