### ISSUE TITLE
Call to undefined method mysqli_stmt::get_result() when mysqlnd is not available

### ISSUE THREAD

**Issue by AndrewPixel** [ADOdb/ADOdb#967] opened 2023-05-07 04:15 UTC
### Description
I can no longer connect to the db.

### Environment
- ADOdb version: 5.22.5
- Driver or Module: mysqli
- Database type and version:  mySQL
- PHP version:  8

### Steps to reproduce
Attempt to connect to the db with

$type = "mysqli";
$db = ADONewConnection($type);
$db->connect("s131.fred.hostingplatform.net", "fred_user", "fred_pwd", "fred_db");

I get this error:

mysqli_query(): Argument #1 ($mysql) must be of type mysqli, bool given at /home/fred/public_html/Decide.It/upload/adodb/drivers/adodb-mysqli.inc.php:1372

### Expected behaviour
A successful connection is made.

### Additional context 
I develop locally using IIS and it works as expected but when I upload the same code (which works with earlier versions of ADOdb) it fails.

**Comment by dregad** [comment] 2023-05-07 08:38
If the code works locally but not on your server, that rules out the problem being caused by a bug in ADOdb.

For the record: the provided code snippet does not allow to reproduce the problem - ADODB_mysqli::connect() does *not* call mysql_query().

The problem is almost certainly caused by an unsuccessful connection (your `$db->connect()` call fails), so the $_connectionId is *false*. You should check the method's return value before continuing with your code
You can also set `$db->debug = true;` before, ADOdb will print an error message that will help you troubleshoot.

**Comment by AndrewPixel** [comment] 2023-05-07 22:30
I turned on debug and got "Could not connect : Access denied for user..."

Thank you for taking the time to help.

In my code I've wrapped the call to connect in a try/catch expecting it to throw an error if it didn't connect (which it didn't)

try {
	$type = "mysqli";
	$db = ADONewConnection($type);
        $db->connect("s131.fred.hostingplatform.net", "fred", "rhy.ES", "fred_db");
} catch (\Throwable $t) {
	echo "Error: " . $t->getMessage(), " at ", $t->getFile(), ":", $t->getLine(), "\n";
}

Instead, is the right way to do this to immediately check for a successful connection?

**Comment by dregad** [comment] 2023-05-08 05:34
You can use exceptions too, read 
https://adodb.org/dokuwiki/doku.php?id=v5:userguide:error_handling&s%5B%5D=exception#exception_trapping

**Comment by AndrewPixel** [comment] 2023-05-09 03:20
For testing, I've simplified the code to:
```
include 'adodb/adodb.inc.php';

$type = "mysqli";
$db = ADONewConnection($type);
$db->connect("s131.fred.hostingplatform.net", "fred_user", "rhyfredES", "fred_db");
$db->EXECUTE("set names 'utf8mb4'");

if (!$db->isConnected()) die('Error: NO!');

$bindVars = array($email);
$sql = "SELECT user FROM admin WHERE email=?";
$rs = $db->Execute($sql, $bindVars);
```

and I get this in the console at the Execute:

<b>Fatal error</b>:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/fred/public_html/tool/upload/adodb/drivers/adodb-mysqli.inc.php:1340
Stack trace:
#0 /home/fred/public_html/tool/upload/adodb/adodb.inc.php(1613): ADODB_mysqli-&gt;_query()
#1 /home/fred/public_html/tool/upload/adodb/drivers/adodb-mysqli.inc.php(1153): ADOConnection-&gt;_Execute()
#2 /home/fred/public_html/tool/upload/login.php(37): ADODB_mysqli-&gt;execute()
#3 /home/fred/public_html/tool/upload/login.php(249): include('/home/fred/...')
#4 {main}
  thrown in <b>/home/fred/public_html/tool/upload/adodb/drivers/adodb-mysqli.inc.php</b> on line <b>1340</b>

So it seems it's connecting to the database but failing when it tries to query it. Sadly I don't know how to go about resolving this. Any help would be appreciated.

**Comment by AndrewPixel** [comment] 2023-05-09 03:30
I just now replaced ADOdb 5.22.5 with the legacy release 5.21.4 and now everything works as expected!

I've no idea why 5.22.5 errors on the production server.

**Comment by AndrewPixel** [comment] 2023-05-09 21:28
mysqlnd wasn't installed. I installed it then tried 5.22 again and it worked.

**Comment by dregad** [comment] 2023-05-10 09:54
For now I have updated the [mysqli driver documentation](https://adodb.org/dokuwiki/doku.php?id=v5:database:mysql), to add a warning that the mysqlnd extension is required.

Planning to add a check in the code, that will stop with a meaningful error when it is not present.

**Comment by dregad** [comment] 2023-05-10 10:06
@AndrewPixel I don't have any environment available where I can actually test this (meaning, the missing mysqlnd). When the change is implemented, would you be able to test and confirm that the updated code works as expected ? It would be appreciated.

**Comment by AndrewPixel** [comment] 2023-05-10 23:08
Yes, I installed mysqlnd on the production server and now it behaves as expected.

My development server is IIS and not only is mysqind not installed it doesn't even appear to be available (though everything still works as expected.)

**Comment by dregad** [comment] 2023-05-11 08:50
> Yes, I installed mysqlnd on the production server and now it behaves as expected.

I'm not sure you understood what I meant. I'm planning to add an extra check in the ADOdb MySQL driver, to ensure that mysqlnd is present when initializing the driver or connecting to the DB, and trigger an error if not.

Since I will not be able to properly test this myself in a real-life scenario, what I would like you to do when the fix is ready, is confirm that the code actually works as expected, i.e. that it correctly detects and reports that mysqlnd is missing in an environment where it is not installed, like your prod server before you fixed it.

> development server is IIS and not only is mysqind not installed it doesn't even appear to be available 

What makes you say that ? It must be, otherwise you would get the same error here as you reported in https://github.com/ADOdb/ADOdb/issues/967#issuecomment-1539330575... Did you check phpinfo() ? You should see something like this:

![image](https://github.com/ADOdb/ADOdb/assets/449891/47543f23-3370-43d2-b393-62d2fad27b4a)

**Comment by AndrewPixel** [comment] 2023-05-11 22:07
Oh, yes I'll test a new version of ADOdb to check that it gives an error if mysqlInd is missing.

Yes you're right, it is in phpinfo. As an extension I can install/disable only php_mysqli.dll (and pdo_mysql.dll).

**Comment by dregad** [comment] 2023-05-24 10:02
Without feedback from you, I assume you don't have time or interest to test. I'll merge the pull request as-is and close this issue, you can always reopen it later if you notice that things are not working as they should.

**Comment by AndrewPixel** [comment] 2023-05-24 21:57
It's not that I don't want to test it. It's that I don't know github well enough to know out how to get the copy I need to test. I looked for a download link but couldn't find one :-(

**Closed** 2023-05-25 14:02 UTC
Labels: bug, mysqli
