### ISSUE TITLE
Adodb using php 7.1 failing silently

### ISSUE THREAD

**Issue by julesbl** [ADOdb/ADOdb#403] opened 2018-03-12 12:47 UTC
I am using ADODB as a database abstraction layer in PHP.

This has been working fine for a long time in a piece of software that I have been supporting.

Recently started using it on a hosting with PHP Version 7.2.3 and ADODB starts failing silently. I'm using 5.20.9 of ADODB.

The only things in the error log are
[Mon Mar 12 12:11:56.302330 2018] [cgi:error] [pid 105831] [client 185.65.110.157:50676] AH01215: 
[Mon Mar 12 12:11:56.302439 2018] [cgi:error] [pid 105831] [client 185.65.110.157:50676] AH01215: adodb.inc.php(1167) : The each() function is deprecated. This message will be suppressed on further calls
[Mon Mar 12 12:11:56.302445 2018] [cgi:error] [pid 105831] [client 185.65.110.157:50676] AH01215: 

The the database is working properly and ADODB claims it has connected.
Fails on simple query.
Changed line 1167 in file adodb.in.php to "foreach($arr as $v) {" and the whole thing sprang to life.

**Comment by joebordes** [comment] 2018-03-12 14:51
Try 5.20.10, I think this has been fixed on that version.

**Comment by dregad** [comment] 2018-03-12 16:17
> using php 7.1 

@julesbl  you mean _7.2_, right ?

> Try 5.20.10, I think this has been fixed on that version.

@joebordes actually now that you mention it, I meant to backport that to 5.20.10, but I think I forgot... so the fix is probably only on master at the moment.

**Comment by dregad** [comment] 2018-03-29 23:57
Closing this as duplicate of #373

**Closed by dregad** 2018-03-29 23:57 UTC
Labels: duplicate, php7
