### ISSUE TITLE
MSSQL ODBC does not respect field aliases

### ISSUE THREAD

**Issue by xow** [ADOdb/ADOdb#141] opened 2015-07-27 06:37 UTC
For MSSQL ODBC the result set returned from a query using an alias for a fieldname will just return the original field name. Other drivers seem to work fine.

```
$rs = $db->Execute("SELECT realname AS aliasname FROM table")
```
```
[fields] => Array
(
        [realname] => test
)
````

**Comment by mnewnham** [comment] 2015-07-27 13:33
I'm assuming your are talking about the odbc_mssql driver,
1. Operating system?
2. Which version of SQL Server?
3. Are you using a DSN type connection?
3. Are you able to determine if its a problem if you bypass ADOdb completely, and just use the odbc driver completely?

**Comment by mnewnham** [comment] 2015-07-27 14:50
The following code snippet seems to produce different results between versions
```php
$db = newAdoConnection('odbc_mssql');
$db->connect('Driver={SQL Server};Server=192.168.10.25','user','password','testdb');

$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;

$SQL = "SELECT user_code my_usercode,description FROM users";
$result = $db->Execute($SQL);
while ($r = $result->fetchRow())
    print_r($result->fetchRow());

```
This seems to be a recursion bug introduced into version 5.19. If you can, I recommend reverting back to  [Version 5.18](http://sourceforge.net/projects/adodb/files/adodb-php5-only) temporarily.

**Comment by xow** [comment] 2015-07-28 01:46
Thanks for the response!

Web server's OS: Windows 7
SQL Server:
```
Microsoft SQL Server 2012 - 11.0.2100.60 (X64) 
	Feb 10 2012 19:39:15 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```
DSN Type connection: Yep, I created it under "System DSNs"
Bypassing ADOdb: Yep the query works fine when directly querying the server

Hmm, unfortunately I still get the same problem in version 5.18. Haven't had time to delve into the code much yet.

**Comment by mnewnham** [comment] 2015-07-28 19:03
Could you first pull this file https://github.com/ADOdb/ADOdb/blob/associative-array-issues/adodb.inc.php and test. Next could you paste a larger code snippet. I cannot reproduce the issue you are having

**Comment by xow** [comment] 2015-07-31 08:35
I tried that file, still AS does nothing, unfortunately. I think the associative values was fixed in #20 ?

Full code https://github.com/xow/moodle/blob/MDL-50307-master/auth/db/auth.php

Cut down:

```
$authdb = ADONewConnection($this->config->type);
$authdb->Connect($this->config->host, $this->config->user, $this->config->pass, $this->config->name, true);
$authdb->SetFetchMode(ADODB_FETCH_ASSOC);
if (!empty($this->config->setupsql)) {
    $authdb->Execute($this->config->setupsql);
}
$rs = $authdb->Execute("SELECT {$this->config->fieldpass} as userpass
                              FROM {$this->config->table}
                             WHERE {$this->config->fielduser} = '".$this->ext_addslashes($extusername)."'");

print_object($rs);
```

Perhaps reproduction requires setting up the ODBC DSN in a certain way?

**Comment by xow** [comment] 2015-07-31 08:37
I should also point out that I'm using 5.19 but with the fix for #20 applied. I tried current 5.20 as well but it didn't work either. Sorry I forgot to specify the version.

**Comment by mnewnham** [comment] 2015-07-31 16:06
Yes indeed, I was clearly asleep when the work was done. I need to step back from this as it makes no sense to me. It implies that either

1. That ADOdb is massaging the SQL statement before execution to remove the aliases.
2. That ADOdb is submitting the query in ADODB_FETCH_NUM status, then the bind function is not assigning the correct fieldnames because of a problem in fields()  (this feels the most likely)
3. That the query is ignoring the aliases.

This does not explain why I can't duplicate this. You did not mention what version of PHP you are using. I've tested with 5.3 and 5.6.

Going with option 2:
Could you grab the sql statement and fetch mode prior to the execution of the query. You should be able to do this in adodb-odbc_mssql.inc.php file, in the _query method (around line 236)

```php
function _query($sql,$inputarr=false)
	{
		global $ADODB_FETCH_MODE;
        print '<pre>';
        print "\n$sql";
        print "\nMODE=$ADODB_FETCH_MODE";
               
        if (is_string($sql)) $sql = str_replace('||','+',$sql);
		return ADODB_odbc::_query($sql,$inputarr);
	}
```

**Comment by xow** [comment] 2015-08-03 07:38
My php version is 5.5.24
```
SELECT PasswordZ as userpass
                                      FROM users
                                     WHERE UsernameZ = 'coswald'
MODE=0
```

**Comment by mnewnham** [comment] 2015-08-03 14:30
Could you now post the top section of the result set, that includes both the fields and the bind section, i.e.
```php
[databaseType] => odbc_mssql
    [bind] => Array
        (
            [my_usercode] => 0
        )

    [dataProvider] => odbc
    [useFetchArray] => 
    [_has_stupid_odbc_fetch_api_change] => 1
    [fields] => Array
        (
            [my_usercode] => 1SELFTC
        )

    [blobSize] => 100
    [canSeek] => 
    [sql] => SELECT user_code my_usercode FROM users
```

**Comment by xow** [comment] 2015-08-04 02:23
```php
ADORecordSet_odbc_mssql Object
(
    [databaseType] => odbc_mssql
    [bind] => Array
        (
            [PasswordZ] => 0
        )

    [dataProvider] => odbc
    [useFetchArray] => 
    [_has_stupid_odbc_fetch_api_change] => 1
    [fields] => Array
        (
            [PasswordZ] => test
        )

    [blobSize] => 100
    [canSeek] => 
    [sql] => SELECT PasswordZ as userpass
                                      FROM users
                                     WHERE UsernameZ = 'coswald'
```

**Comment by mnewnham** [comment] 2015-08-08 17:36
I've still no idea what's going on, could you run my program
against your database and post the results.

```php
$db = newAdoConnection('odbc_mssql');
$db->debug = true;

/*
 * Put your connection parameters here
*/
$db->connect('Driver={SQL Server};Server=192.168.10.25','user','password','testdb');

$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;

$SQL = "SELECT PasswordZ as userpass
                                      FROM users
                                     WHERE UsernameZ = 'coswald'";

$result = $db->Execute($SQL);
$r = $result->fetchRow();
print_r($r);
```

**Comment by xow** [comment] 2015-08-12 09:14
I couldn't get it to work using lower case connect (not sure what the correct way to format that connection string would be). I tried a few combinations based on the documentation but nothing seemed to work.

```
$db->Connect('users_odbc','sa','moodle','',true);
```

Using upper case Connect it gives me
```
Array
(
    [PasswordZ] => test
)
```

Perhaps this gives more insight?

**Comment by mnewnham** [comment] 2015-08-12 14:58
1. I noticed that you are forcing it to establish a new connection, is that deliberate?
2. Could you confirm that you are using the Microsoft ODBC driver for SQL server. I know you are using windows, but for example, this driver issue [http://lists.ibiblio.org/pipermail/freetds/2010q2/025720.html] is exactly what you describe.
3. Could you try SELECT [PasswordZ] as [userpass]

**Comment by xow** [comment] 2015-08-13 09:21
1. Not sure exactly why, no difference either way
2. Using [ODBC Data Source Administrator](https://msdn.microsoft.com/en-us/library/ms714024(v=vs.85).aspx) to create it and [Microsoft® ODBC Driver 11 for SQL Server® - Windows](http://www.microsoft.com/en-au/download/details.aspx?id=36434) to connect to it
3. Same result :(

Do you think it is possible it's related to connect vs. Connect?

**Comment by mnewnham** [comment] 2015-08-13 15:04
1. PHP methods and functions are not case sensitive, connect,Connect, cONNect are all the same thing. 
2. Could you please bypass the DSN you set up and access the driver directly to see if it is a driver configuration issue.
3. If you are getting different results between connect and Connect, please post the $db->debug logs for both.

**Comment by xow** [comment] 2015-08-14 08:05
Oh ha of course, makes sense. Yeah same results for the call no matter the case. Just had to call it in a different way.

```
$db = newAdoConnection('mssqlnative');
$db->connect('mssql99.test.in.moodle.com','sa','moodle','auth_db');
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;
$SQL = "SELECT [PasswordZ] as [userpass]
                                      FROM users
                                     WHERE UsernameZ = 'coswald'";
```

Gives me

```
Array
(
    [userpass] => test
)
```

It also works without the brackets in the query. Looks to me like it must be the odbc_mssql driver.

**Comment by mnewnham** [comment] 2015-08-18 22:35
Absent any further discoveries on this subject, and the time I've put into this. I'm afraid I must close this as un-reproducible. If you come across anything that might assist in diagnosis, feel free to re-open the issue and post

**Closed by mnewnham** 2015-08-18 22:35 UTC
Labels: bug, not reproducible

**Comment by fwabendo** [comment] 2016-04-25 15:51
I am getting similar aliase challenge with 5.20 and php 7.0

` [sql] => SELECT  
					  top 1 [id] AS SelectLabel 
				FROM [user_role]
				 WHERE [status_id] = '1'  AND [guest] = '1' 
				
    [compat] => 
    [dataProvider] => odbc
    [fields] => Array
        (
            [id] => 1
        )`

**Comment by mnewnham** [comment] 2016-04-25 16:53
Can you provide a bigger sample code statement including the connect statement, platform, driver, etc.

**Comment by fwabendo** [comment] 2016-04-25 17:14
platform is ubuntu 14  driver unixodbc and freetds

`$this->_conn = ADONewConnection("odbc_mssql");
$dsn = "Driver={SQL Server};Server={$this->getHost()};Database={$this->getName()};Port=1433";
$this->_conn->Connect($dsn,$this->getUser(),$this->getPassword());
$this->_conn->SetFetchMode(ADODB_FETCH_ASSOC);`

**Comment by mnewnham** [comment] 2016-04-25 23:33
Is this only a problem with PHP 7? 
are you able to test with PHP 5.x?

Could you look at [this question on stackoverflow](http://stackoverflow.com/questions/12200072/php-odbc-not-accepting-alias-on-column-name-with-space). Whilst it is not quite the same issue as you are having, there is an answer that you could try.

**Comment by fwabendo** [comment] 2016-04-26 06:38
Adding +'' before AS aliase  works  but I have not tried with numreric functions like select count(*) AS 'label'.
Though this is a tideous solution because i have to go and change several model functions and also test where +'' does not apply.

I am yet to point out  other challenges with php 7  because i am dealing with a big model source code.

Thanks for the support.

**Comment by mnewnham** [comment] 2016-04-27 23:57
My only thought with this issue is that you have shown that the behavior of the driver has changed between PHP 5.x and 7. This is likely not and ADOdb problem, but we have in the past and can possibly continue to, added version specific fixes to drivers. This is obviously dependent on someone like yourself having the time to actually identify the root cause of the problem.  You might have better luck posting a question on the UnixODBC site

**Comment by anvilvapre** [comment] 2016-07-26 20:43
odbc_fetch_array has the same problem, not sure if that uses ado, thought it didn't.
using php7, unixodbc to connect to mssql. odbc_field_name also does not return the alias name but the original column name without table alias prefix.

**Comment by imwalid** [comment] 2018-04-07 00:11
I faced a similar problem and, by sheer trial and error, I realized that if the alias is a reserved word the query fails. Reserved words include "number" and "n" and "string" and "s" and "select". These are the labels that can be made to work when quoted.

**Comment by yopop666** [comment] 2020-06-05 17:52
Faced similar problem. After hours of digging the 4th parameter of [**odbc_connect**](https://www.php.net/manual/en/function.odbc-connect.php) did the trick in my case choosing **SQL_CUR_USE_ODBC**.
