### ISSUE TITLE
PHP Named Parameter support changed since ADODB 5.20.*

### ISSUE THREAD

**Issue by rkingy** [ADOdb/ADOdb#986] opened 2023-06-11 21:50 UTC
### Description
We've recently upgraded ourADODB version from v5.20.21 => v5.22.6 but finding that the named parameter support is no longer available.

Is there some magical setting we can use to enable this?

At the moment we are getting the following errors:

`(HY093) SQLSTATE[HY093]: Invalid parameter number: parameter was not defined.`

With a query like

`SELECT * FROM table WHERE contentID = :contentID`

Using code like

`$db->query($query, [':contentID' => $this->contentID])`

### Environment
- ADOdb version: 5.22.6
- Driver or Module: PDO
- Database type and version: Mysql v 8.0.33-1.el8
- PHP version: 8.2
- Platform: Centos7

* [ ] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **master** branch / **hotfix** branch  
  ⚠️ Keep only the applicable option(s), i.e. where you actually tested and remove the others)
  
  Actually seems to be fixed in latest commit 12 June.. is this correct?

**Comment by dregad** [comment] 2023-06-12 09:10
This is a known issue, please see #880 for details. It was introduced in 5.21.1 by the patch for #705 (099d06fc8f3f5fa8e82c0064c1b9148e89729b4c).

It took me a while to figure things out, because I was initially not able to reproduce the problem at all, until I realized that PDO does not throw an exception when a query with named parameters is executed using a numerically-indexed array on PHP 7.4 (which I was using for my tests); the problem only occurs with PHP 8.0+.

The bug has been fixed in *master* branch (7a14eeb476fcf44077722d8726f52a88c5f7f7ec), and will be available in the upcoming 5.23.0 release. The patch was not back-ported to 5.22 branch because it introduces a new functionality (ability to select parameter type).

Until then, you have the following workarounds:
- for best portability, you should generally be using *ADOConnection::param()* to introduce query parameters, instead of hardcoding them in your queries.
- revert 099d06fc8f3f5fa8e82c0064c1b9148e89729b4c or comment-out the `$inputarr = array_values($inputarr);` statement in ADODB_pdo::_query() (adodb-pdo.inc.php)
- cherry-pick commit 7a14eeb476fcf44077722d8726f52a88c5f7f7ec or use code from *master* branch
- use PHP 7.4

I'm going to close this as duplicate of #880.

**Closed by dregad** 2023-06-12 09:10 UTC
Labels: bug, duplicate, PHP8

**Comment by rkingy** [comment] 2023-06-12 21:10
Thanks @dregad  this information solves quite a headache for us! We'll probably use latests master branch, or wait for 5.23. Hopefully not far away?

**Comment by dregad** [comment] 2023-06-12 22:56
> wait for 5.23. Hopefully not far away?

Nearly there... A couple features to wrap. But no commitment on a release date (I've postponed it too many times already)
