### ISSUE TITLE
each() This function has been DEPRECATED as of PHP 7.2.0.

### ISSUE THREAD

**Issue by nickchangtw** [ADOdb/ADOdb#398] opened 2018-03-01 05:10 UTC
each() This function has been DEPRECATED as of PHP 7.2.0. Relying on this function is highly discouraged.
each() function has been deprecated. So, it cannot be used in PHP 7.2, instead use foreach() function.
Please fix, Thanks

**Comment by atrol** [comment] 2018-03-01 07:07
This is fixed https://github.com/ADOdb/ADOdb/commit/d9cc6c66ec08e5a517f8fa4503345ead992e2a62 but not yet released.

**Comment by dregad** [comment] 2018-03-01 09:12
Duplicate of #373

**Closed by dregad** 2018-03-01 09:12 UTC
Labels: duplicate
