### ISSUE TITLE
Versions and releases

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#627] opened 2020-08-20 15:39 UTC
Many thanks for Adodb - it's still so usefull for many of my projects. 
Could you please help me with a question on the repository. 

I have installed Adodb via composer. I am not sure which version was installed - most files are tagged with 
`@version v5.20.0 28-Nov-2015` .
.. for example adodb.inc.php

Here, on Github - if I check adodb.inc.php it is tagged with 
`@version v5.21.0-dev ??-???-2016`

So this rises some questions for me:

- Which composer repo should I use to get the latest version
- Is the master branch a production branch (doesn't look like that if I look at the version tags)
- And if not where can I download the latest stable release?

It would be very helpful to have releases on Github
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by dregad** [comment] 2020-08-20 21:22
Duplicate of #628

**Closed by dregad** 2020-08-20 21:22 UTC
Labels: duplicate
