### ISSUE TITLE
Composer command bring older version which has bugs

### ISSUE THREAD

**Issue by yshaool** [ADOdb/ADOdb#648] opened 2020-12-01 20:30 UTC
I just recently installed using composer require adodb/adodb-php ^5.20 and it brought older version. I had a bug with pageExecute and use of order by that once I set the version for the last one was fixed.

Maybe change at home page and to:
composer require adodb/adodb-php ^5.20.18

**Comment by mnewnham** [comment] 2020-12-06 20:34
Duplicate of #645

**Closed by mnewnham** 2020-12-06 20:34 UTC
Labels: duplicate
