### ISSUE TITLE
mysqli driver with PHP7.0 reports warning (and seems to fail to work)

### ISSUE THREAD

**Issue by nacc** [ADOdb/ADOdb#218] opened 2016-03-23 17:38 UTC
PHP Warning:  mysqli_real_connect() expects parameter 6 to be integer, string given in /usr/share/php/adodb/drivers/adodb-mysqli.inc.php on line 123

with Ubuntu 16.04. Simply casting $this->port to (int) fixes the issue, but unsure if it's the right fix.

**Comment by dregad** [comment] 2016-03-23 23:40
Can you please...
- indicate which version of ADOdb you're using
- check if the problem can be replicated with latest development version (master branch)
- provide a code snippet to reproduce the issue

**Comment by nacc** [comment] 2016-03-24 01:19
On Wed, Mar 23, 2016 at 4:40 PM, Damien Regad <notifications@github.com> wrote:
>
> Can you please...
>
> indicate which version of ADOdb you're using

Ubuntu 16.04 is at 5.20.3 as is Debian unstable. For reference, Ubuntu
16.04 and Debian stretch (I believe) are going to be PHP7.0 only.

> check if the problem can be replicated with latest development version (master branch)

I'm not actually a PHP developer, I just own the PHP7 migration in
Ubuntu 16.04. As far as I can tell, the code line in question is
unchanged with master. I will see if I can spin up an env to test with
pure upstream, but it's not the highest priority for me right now
(removing PHP5 is :)

> provide a code snippet to reproduce the issue

I saw this while attempting to test cacti with php7
(http://www.cacti.net/index.php), I'm not sure of a simple testcase
although for reference,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815987 is the Debian
bug report, which is related. PHP7.0.4 though does have the function
defined as:

proto bool mysqli_real_connect(object link [,string hostname [,string
username [,string passwd [,string dbname [,int port [,string socket
[,int flags]]]]]]])

**Comment by dregad** [comment] 2016-03-25 01:03
@mnewnham typecasting to int seems like the most simple solution to the issue, but I'm wondering if we should not make sure that ADOConnection::$port is of the right type instead when assigning it in ADOConnection::connect()/pConnect() or ADONewConnection(). What do you think ?

**Comment by nirgal** [comment] 2016-03-25 10:21
Is using the string version of the port number supported by any driver? I mean a string from `/etc/services`. Probably not, but it might be worth checking if you are working on this...

**Comment by nacc** [comment] 2016-03-25 15:23
On Fri, Mar 25, 2016 at 3:21 AM, nirgal <notifications@github.com> wrote:

> Is using the string version of the port number supported by any driver? I
> mean a string from /etc/services. Probably not, but it might be worth
> checking if you are working on this...
>
This *should* be pretty easy to test with cacti and changing the default
driver -- but I may not get to it until Monday.

**Comment by mnewnham** [comment] 2016-03-25 15:37
Mysql itself does not support the use of a service alias for [port](https://dev.mysql.com/doc/refman/5.5/en/connecting.html), and It would appear that mysqli_real_connect only supports only integer values so:

 - Yes, we should cast the value to integer,  in adodb-mysqli::_connect
 - If we could trap a cast failure, that would be nice,

**Comment by nirgal** [comment] 2016-03-25 16:47
@mnewnham : The link you sent is about mysql command line client. I just tested it and port string `mysql` does work here!
```
$ mysql -h localhost -u test --port 3306 -p
Enter password: 
Welcome to the MySQL monitor....
$ mysql -h localhost -u test --port mysql -p
Enter password: 
Welcome to the MySQL monitor....
```
but theoretically, what should be tested are adodb php drivers, including postgreSQL, not the command line.

I support the idea to have the cast in adodb-mysqli::_connect rather than have it globally.
But I have no problem with a possible decision to stick to numbers when talking about ports. Especially since popular mysql drivers restrict this. Just be aware of the change.

**Comment by dregad** [comment] 2016-03-25 19:29
>  Yes, we should cast the value to integer, in adodb-mysqli::_connect

Sounds like the easiest approach, with lower risk of regression.

> If we could trap a cast failure, that would be nice,

Is it even possible for a cast to fail ?

> theoretically, what should be tested are adodb php drivers, including postgreSQL, not the command line.

Yep. that's what I'm concerned about, that's where the risk of regression is - and the effort of the testing task makes me lean towards the simpler approach. Call me lazy ;)

**Comment by mnewnham** [comment] 2016-03-25 20:02
> Is it even possible for a cast to fail ?

I meant that if anything casted to zero  e.g. (int)'mysql',  we could perhaps in this case default to 3306?

**Closed** 2016-04-09 08:18 UTC
Labels: bug, mysql, php7
