### ISSUE TITLE
Table name normalization feature is not consistant

### ISSUE THREAD

**Issue by EyeAndTea** [ADOdb/ADOdb#129] opened 2015-06-22 22:37 UTC
The function "ADOConnection::MetaColumns" has a normalization parameter that allows one to disable case normalization, which works by either converting to uppercase or lowercase. However other functions of the same logical group such as "ADOConnection::MetaColumnNames" have no such parameter and when they make the call to "ADOConnection::MetaColumns" they set the parameter themselves. This makes external code that relies on MetaColumns as well as MetaColumnNames for example buggy, unless the external code does not set the normalize parameter on MetaColumns. This is not a bug in the ADODB code, but a bug in the ADODB algorithm.

Fixing this would require making all such functions take a normalize parameter, but this would require changing the function signatures which would break backward compatibility, unless the normalize parameter is added at the end which we think is unacceptable. A second approach would be to create new functions that take the normalize parameters, but we are uncomfortable adding new signatures to the API. A third approach would be to encode the parameter in the table name. For example, if the table name is prefixed with "<>" do not normalize. We would like to hear the thoughts of the project maintainer on this. We are a small company and forking the project would be expensive to us, thus we are doing our best to only make proposals that are likely to get accepted, hence we are waiting and shall be taking any thoughts of the project maintainer seriously.

**Comment by dregad** [comment] 2015-06-23 10:30
I agree that changing a function's signature must be avoided. However, can you clarify why you are saying that adding a parameter at the end is not acceptable ? It sounds to me like the least intrusive approach.

Adding a new function and deprecating the old one may work, but I'm also not a big fan of adding too many API calls.

I don't really like the idea of changing the meaning of an existing parameter by adding a prefix.

Just thinking out loud here as I did not look into details, but another approach could be to allow the `$table` parameter to be either *string* (tablename) or *array(string, boolean)*. It's kind of a hack, but may provide the flexibility while maintaining backwards compatibility by checking the variable's type with `is_array($table)` and setting $normalize if the array's 2nd param is true.

**Comment by CreatrixTeam** [comment] 2015-06-23 12:00
Thank you for responding.

Regarding adding new parameter at the end, the reason we are against this is due to what one might call "semantic distance". Take the function "MetaColumnNames" as an example. The following is a verbatim of the signature line in the base class:

function MetaColumnNames($table, $numIndexes=false,$useattnum=false /* only for postgres */) {

The first parameter is the table name, the second parameter seems to be indicating the format of the returned result, and the third parameter is something special for some databases as indicated in the code comments. Only the table name parameter is mandatory. The semantic distance between table name and the second and third parameters is far greater than the semantic distance between table name and the question of whether the same said name is to be normalized or not. In other words a developer is more likely to want to specify the normalization parameter than specify the format of the returned results or the database specific parameter, but now the developer would be forced to specify all unrelated parameters before specifying the related parameter to the only mandatory parameter. Of course this would have not been an issue if all parameters were required. Further more note that in the function MetaColumns itself the normalization parameter immediately follows the table name parameter and it is desired for obvious reasons to standardize parameter order in APIs.

Regarding adding new function signatures we are also unhappy with this. Further more, if we choose to do so we would have to standardize all related functions' signatures beginning them with verbs such as 'get'.

Regarding the prefix, we were thinking about another problem down the line of integrating the quotation feature of ADODB Data Dictionary in ADODB. Regarding the approach itself we later changed our mind to use, instead of a prefix, another quotation for the purpose, such as "<". For example if the table name is tableName, we are foreseeing the following usage (note we are using ' to mean back-quotes):
- tableName:   for when default behavior is desired.
- 'tableName':   for when quotation is desired for the purpose of avoiding problems with reserved keywords, yet normalization is also required.
- <tableName>:   for when normalization is required, but not quotation because the table name is not expected to be a keyword.
- '<tableName>':   for when quotation is desired for the purpose of avoiding problems with reserved keywords, and normalization is also required.

The reason behind the above is because on some databases quotation not only protects from reserved keyword semantic errors but also turns off case normalization that is done by the database itself, rather than ADODB.

Regarding the array approach, we would usually code in strongly typed fashion. Meaning, the data types of parameters and return values are never changed. However we understand the advantage of keeping the meaning of the table name intact.

Thank for your continued participation. We are waiting for your response.

**Comment by ipso** [comment] 2015-06-23 15:08
What about just setting a "normalization" flag in the datadict object itself that all related functions read when they are called? 

Another approach could be to break out the normalization procedure into its own wrapper function that can be called whenever the developer wants, ie:

$datadict->normalize( $datadict->MetaColumns() );

What exactly is the use case for "normalizing" the column names anyways? I understand that some databases may be case sensitive or have different reserved words, but if anything that should naturally discourage normalization to avoid breaking things...

**Comment by CreatrixTeam** [comment] 2015-06-23 19:48
Thank you for your participation. A flag is inappropriate for this; this is not a configuration. The decision to normalize or not happens on function call time, not before, hence it must be a parameter. 

As for "$datadict->normalize( $datadict->MetaColumns() );" suggestion, please re read our previous two comments, and refer to the referred code. You may also want to refer to issue 126, but that is not necessary.

Regarding the why, case normalization is already part of the ADODB library, but the current API is not homogeneous, and can lead to bugs in external code. This already happened with AXMLS. We are simply seeking to clean up the API, and any bugs in code and specifications/algorithms.

**Comment by CreatrixTeam** [comment] 2015-06-24 13:09
If we were not clear, a simplified view and statement of the problem is:

It is currently impossible to retain case sensitivity with table names while utilizing all of ADODB's functionality. ADOConnection::MetaColumnNames is an example of that.

**Comment by ipso** [comment] 2015-06-24 15:03
In my opinion trying to add some sort of table name syntax like "[]" or "<>" is not a good approach, nor is using an array for table names rather than a string. They both feel like hacks that will clutter things up and cause even more confusion later on, not to mention non-obvious and a documentation burden.

I would vote for staying consistent and adding a $normalize argument to each function that you feel needs it. The "semantic distance" argument doesn't hold water, the example given only has three arguments currently, if it had 10+ I might be concerned, but 4 arguments is nothing and ADODB is already riddled with functions that accept many more than that, as is PHP itself.

Without more evidence and real-world use case examples, it seems to me like this affects a tiny fraction of the real-world installations, cluttering up the API with additional functions or trying to deprecate existing functions in favor of others seems like overkill.

**Comment by CreatrixTeam** [comment] 2015-06-24 17:16
One is rather confused by your comment @ipso. Please read carefully what we wrote, and examine the referenced code. At this point you should also carefully examine our comments and proposals about https://github.com/ADOdb/ADOdb/issues/126. One suggests you read the documentation about ADODB Data Dictionary.

**Comment by mnewnham** [comment] 2018-07-22 22:15
As there has been no participation in this thread in 2 years, I am closing it. If you are interested in reopening it, feel free to

**Closed by mnewnham** 2018-07-22 22:15 UTC
