### ISSUE TITLE
AutoExecute for MySQLi failed

### ISSUE THREAD

**Issue by zhujack** [ADOdb/ADOdb#796] opened 2022-01-25 15:12 UTC
After switching to MySQLi driver, AutoExecute always fails with the following error message:

    "Commands out of sync; you can't run this command now"

This problem was reported before: #388  
But, it has not been fixed as of version 5.21.3.  

Manually adding $rs->Close(); before $this->Execute ($sql); in AutoExecute function fixes the problem. 

I am using ADOdb 5.21.3 and 10.4.21-MariaDB. 

Thanks,

Jack

**Comment by dregad** [comment] 2022-01-28 21:33
> This problem was reported before: #388
> But, it has not been fixed as of version 5.21.3.

Since you found the older issue, you may also have noticed that it was closed as _won't fix_ (see https://github.com/ADOdb/ADOdb/issues/388#issuecomment-370760669), hence it should be no surprise that it's not been fixed...

Consequently, I'm closing this issue as duplicate of #388. I do not mind reopening that, provided that you submit a pull request to fix the problem.

**Closed by dregad** 2022-01-28 21:33 UTC
Labels: duplicate
