### ISSUE TITLE
Error when closing recordset from destructor

### ISSUE THREAD

**Issue by marinaglancy** [ADOdb/ADOdb#170] opened 2015-12-15 02:52 UTC
I have reported it also in #168 and was asked to separate issues, so here it goes.

The introduction of the destructor https://github.com/ADOdb/ADOdb/commit/6e301f59ef3e2088654794979aea1611d19650a1 led to unittests failures in Moodle on mysqli and mssql. The errors occur in _close() methods: "mysqli_more_results() expects parameter 1 to be mysqli, boolean given" and "mssql_free_result(): 1842 is not a valid MS SQL-result resource"

The most of the drivers either mute errors by using @ or test that connection/query is not empty. Looking at the code I can see that there are more drivers that lack such checks (we don't run tests on every single driver in moodle):
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-informix72.inc.php#L493
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-mssql.inc.php#L1054
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-mssqlnative.inc.php#L1077
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-mysqli.inc.php#L1060

I'm not sure what is the preferred way to fix this. I would just add @ in front of each of these line and, for extra safety, change the destructor itself to call @$this->Close(); - in case of Moodle I don't think we benefit from this destructor at all. We need to patch adodb in Moodle before the end of this week when we plan our release, I'm reporting this issue here so maybe you can recommend what is the best way to do it.

The unittest in Moodle actually tests our plugin that uses adodb, I did not try to reproduce this problem on adodb as it is, however I need to say that we don't make any modifications to adodb when importing it in moodle. Here is the link to the issue in our tracker: https://tracker.moodle.org/browse/MDL-52286

**Comment by marinaglancy** [comment] 2015-12-15 03:15
Update: I found that it happens in moodle because we sometimes forget to close recordset before closing connection, which is our fault too. I still insist on this change in adodb because destructor should not cause such errors.

**Comment by dregad** [comment] 2015-12-15 08:13
Thanks for opening a separate issue.

> in case of Moodle I don't think we benefit from this destructor at all 
> [...]
> we sometimes forget to close recordset before closing connection, which is our fault too.

AFAIK, this is normally not a problem unless you're using persistent connections.

> I still insist on this change in adodb because destructor should not cause such errors.

You're absolutely right.

> We need to patch adodb in Moodle before the end of this week when we plan our release

Not sure I'll be able to find the time to release a hotfix by then, but I'll do my best.

**Comment by marinaglancy** [comment] 2015-12-15 09:26
thanks you, don't worry about the hotfix, just a suggestion from you will be good as which route to follow. At the moment we settled on @ in the destructor, maybe not the best but the safest

**Comment by dregad** [comment] 2015-12-20 17:53
@marinaglancy Hopefully fixed in above-mentioned commits (see *hotfix/5.20.2* branch). Let me know if your automated tests pass with that. Feel free to reopen if not.

For the record, I was not able to reproduce the PHP warning you mentioned, so your posting of a code snippet that would allow triggering of the error would be appreciated in case the bug is still present on your side.

**Comment by aag1091** [comment] 2015-12-29 14:41
@dregad I am also getting the same error. 

When I checked the documentation for mssql_free_result
http://php.net/manual/en/function.mssql-free-result.php

I found that it needs a the actual response object reference instead of the boolean that is being passed now.

Below is the warning message that is being thrown by php.

```
E_WARNING: mssql_free_result() expects parameter 1 to be resource, boolean given {"code":2,"message":"mssql_free_result() expects parameter 1 to be resource, boolean given","file":"/www/files/vendor/adodb/adodb-php/drivers/adodb-mssql.inc.php","line":1056} 
```

**Comment by dregad** [comment] 2015-12-29 15:16
Duh. I cleared the _queryID attribute *before* calling `mssql_free_result()` sorry about that. I don't have access to a mssql setup, so I couldn't actually test that.

Can you kindly confirm that 2caa6859872a3ea0fc1638ac4db01a9925b2dd07 actually fixes the issue ?

**Comment by aag1091** [comment] 2015-12-29 20:56
@dregad thanks the fix that you provided is working pretty well.

Can you release it?

**Comment by marinaglancy** [comment] 2015-12-30 00:11
Hello, my apologies for not responding earlier, I was on holidays without internet. Here is an example of code from our unittest that demonstrates the error (with removed assertions):

        $authdb = ADONewConnection($this->config->type);
        $authdb->Connect($this->config->host, $this->config->user, $this->config->pass, $this->config->name, true);
        $authdb->SetFetchMode(ADODB_FETCH_ASSOC);
        $sql = "SELECT * FROM {$this->config->table}";
        $rs = $authdb->Execute($sql);
        $fields = $rs->FetchRow();
         //$rs->Close();
        $authdb->Close();
        $rs = null; // This calls destructor.

As I said, we were closing the connection without closing the recordset. If you uncomment the line, there are no errors. 

I can confirm that mysql fix resolves our problem. I am not able to test on mssql at the moment but I can pass to my collegues

**Comment by aag1091** [comment] 2015-12-30 13:10
FYI I tested it only for mssql and it works pretty well.

**Comment by dregad** [comment] 2016-01-01 23:07
Thanks for your feedback. The above-mentioned fix is included in 5.20.3 (just released).

**Closed by dregad** 2016-01-01 23:07 UTC
Labels: bug, informix, mssql, mysql

**Comment by aag1091** [comment] 2016-01-04 02:33
@dregad Thank You very much for the prompt reply.

**Comment by marinaglancy** [comment] 2016-01-05 06:37
Hello, sorry again for the delays with the answers, it's a holidays season. Moodle unittests still do not pass on mssql with an error "mssql_free_result(): 1626 is not a valid MS SQL-result resource"

Here is the more detailed backtrace:
https://tracker.moodle.org/browse/MDL-52619?focusedCommentId=388381&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-388381

**Comment by dregad** [comment] 2016-01-05 11:02
Hi Marina,

Troubleshooting this is difficult for me because, as mentioned before, I don't have a MSSQL platform for testing. Your failure report is also surprising since @aag1091 says it works for him. Can you do a var_dump() of $this->_queryID at beginning of _close() method ?
