### ISSUE TITLE
Function strcmp() throws deprecation error when upading DB field to null

### ISSUE THREAD

**Issue by redpl** [ADOdb/ADOdb#1027] opened 2024-04-16 10:25 UTC
### Description
Deprecated: strcmp(): Passing null to parameter #1 ($string1) of type string is deprecated in adodb-active-record.inc.php on line 1081 is thrown when nullable string field is set to null

### Environment
- ADOdb version: 5.22.7
- Driver or Module: 10.4.32-MariaDB - mariadb.org binary distribution 
- Database type and version: MySQL 5.7
- PHP version: 8.2.12
- Platform: Windows

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest)

### Steps to reproduce
```
$model->image = null;
$model->Save();
```

### Expected behavior
Most likely the line:
```
if (isset($this->_original[$i]) && strcmp($val,$this->_original[$i]) == 0) {
       continue;
}
```
should be changed to:
```
if (isset($this->_original[$i]) && !is_null($val) && strcmp($val,$this->_original[$i]) == 0) {
	continue;
}
```
### Additional context 
Add any other information relevant to the problem here.

**Comment by dregad** [comment] 2024-04-16 15:21
@redpl it sounds like the issue you're reporting is a duplicate of #1021, can you please confirm that commit 172489c55d634b5d01b1f32c8717949784c23396 fixes the issue for you ? 

FYI, it will be part of upcoming version 5.22.8, to be released soon. Download it from here to test: https://github.com/ADOdb/ADOdb/tree/hotfix/5.22.

**Comment by dregad** [comment] 2024-04-24 09:06
@redpl You did not provide any feedback, so I'm closing this issue assuming you agree that this is indeed a duplicate of #1021.

**Closed by dregad** 2024-04-24 09:06 UTC
Labels: triage
